ALTER TABLE hotels
ADD COLUMN IF NOT EXISTS gallery JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS group_title VARCHAR(255),
ADD COLUMN IF NOT EXISTS group_subtitle TEXT,
ADD COLUMN IF NOT EXISTS periods JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS display_order INTEGER DEFAULT 0;
