-- Import frontend package data into the database without duplicating existing packages.
-- Run this file once in pgAdmin Query Tool or with psql.

ALTER TABLE packages ADD COLUMN IF NOT EXISTS country VARCHAR(100) DEFAULT '';
ALTER TABLE packages ADD COLUMN IF NOT EXISTS destination VARCHAR(255) DEFAULT '';
ALTER TABLE packages ADD COLUMN IF NOT EXISTS region VARCHAR(100) DEFAULT '';
ALTER TABLE packages ADD COLUMN IF NOT EXISTS force_category VARCHAR(100) DEFAULT '';
ALTER TABLE packages ADD COLUMN IF NOT EXISTS hide_price BOOLEAN DEFAULT false;
ALTER TABLE packages ADD COLUMN IF NOT EXISTS card_title VARCHAR(255) DEFAULT '';
ALTER TABLE packages ADD COLUMN IF NOT EXISTS card_subtitle VARCHAR(255) DEFAULT '';
ALTER TABLE packages ADD COLUMN IF NOT EXISTS badge_text VARCHAR(100) DEFAULT '';
ALTER TABLE packages ADD COLUMN IF NOT EXISTS hotel_name VARCHAR(255) DEFAULT '';
ALTER TABLE packages ADD COLUMN IF NOT EXISTS hotel_meal VARCHAR(255) DEFAULT '';
ALTER TABLE packages ADD COLUMN IF NOT EXISTS hotel_nights VARCHAR(100) DEFAULT '';
ALTER TABLE packages ADD COLUMN IF NOT EXISTS sgl_price VARCHAR(100) DEFAULT '';
ALTER TABLE packages ADD COLUMN IF NOT EXISTS dbl_price VARCHAR(100) DEFAULT '';
ALTER TABLE packages ADD COLUMN IF NOT EXISTS tpl_price VARCHAR(100) DEFAULT '';
ALTER TABLE packages ADD COLUMN IF NOT EXISTS package_group_id VARCHAR(100) DEFAULT '';
ALTER TABLE packages ADD COLUMN IF NOT EXISTS package_group_title VARCHAR(255) DEFAULT '';
ALTER TABLE packages ADD COLUMN IF NOT EXISTS package_group_subtitle TEXT DEFAULT '';
ALTER TABLE packages ADD COLUMN IF NOT EXISTS package_group_short_title VARCHAR(100) DEFAULT '';
ALTER TABLE packages ADD COLUMN IF NOT EXISTS included JSONB DEFAULT '[]'::jsonb;
ALTER TABLE packages ADD COLUMN IF NOT EXISTS excluded JSONB DEFAULT '[]'::jsonb;
ALTER TABLE packages ADD COLUMN IF NOT EXISTS flight_details JSONB DEFAULT '[]'::jsonb;

INSERT INTO packages (title, name, backend_name, route, duration, transfer, transfer_reduction, start_price, programme, price, country, destination, region, force_category, hide_price, card_title, card_subtitle, badge_text, hotel_name, hotel_meal, hotel_nights, sgl_price, dbl_price, tpl_price, package_group_id, package_group_title, package_group_subtitle, package_group_short_title, visibility, image, options, itinerary, included, excluded, flight_details, display_order)
SELECT
  'Turkey Package: 5 Nights / 6 Days Sharm + Cairo',
  'Turkey Package: 5 Nights / 6 Days Sharm + Cairo',
  '5 GECE 6 GÜN SHARM + KAHİRE TURU - 4 GECE SHARM + 1 GECE KAHİRE',
  'Turkey (SAW) → Sharm El Sheikh → Cairo',
  '5 Nights / 6 Days',
  'Flight + Airport Transfers + Bus to Cairo',
  'Flight: 11:00 SAW → SSH Air Cairo with 20 KG baggage. Return flight will be confirmed.',
  'From 799 USD',
  'Extra Tours: ATV Safari + Bedouin Night (25$) | Ras Mohammed Boat Trip + Diving (40$) | Water Sports Package (70$) | Dahab Tour (25$) | Nile Dinner Cruise (25$)',
  'From 799 USD',
  'Turkey',
  'Sharm El Sheikh + Cairo',
  'others',
  'others',
  false,
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  'Published',
  '/images/packages/turkey-package-1.webp',
  '[{"title":"Hotel Options / Price Per Person","rows":[{"city":"Sharm + Cairo","nights":"4 + 1","hotel":"Park Regency Resort 5* + Hilton Cairo 5*","meal":"AI + BB","sgl":"+220 USD","dbl":"949 USD","tpl":"949 USD"},{"city":"Sharm + Cairo","nights":"4 + 1","hotel":"Marriott Renaissance Golden 5* + Hilton Cairo 5*","meal":"AI + BB","sgl":"+200 USD","dbl":"929 USD","tpl":"929 USD"},{"city":"Sharm + Cairo","nights":"4 + 1","hotel":"Safir Waterfalls Resort 5* + Hilton Cairo 5*","meal":"AI + BB","sgl":"+150 USD","dbl":"869 USD","tpl":"869 USD"},{"city":"Sharm + Cairo","nights":"4 + 1","hotel":"Safir Waterfalls Resort 5* + Amarante Pyramids 5*","meal":"AI + BB","sgl":"+140 USD","dbl":"829 USD","tpl":"829 USD"},{"city":"Sharm + Cairo","nights":"4 + 1","hotel":"Queen Sharm Resort 4* + Flamenco Cairo Hotel 4*","meal":"AI + BB","sgl":"+130 USD","dbl":"799 USD","tpl":"799 USD"}]}]'::jsonb,
  '[{"day":"Day 1","title":"Arrival to Sharm El Sheikh","details":["Meeting at Istanbul Sabiha Gökçen Airport and flight to Sharm El Sheikh.","Airport welcome, hotel transfer and check-in.","Included city tour: Old Market, El Sahaba Mosque and Farsha Cafe."]},{"day":"Day 2","title":"Free Day in Sharm","details":["Breakfast and free time to enjoy the beach, pool and all-inclusive hotel services.","Optional activities: ATV Safari, Bedouin Night, Ras Mohammed boat trip, diving, water sports or Dahab tour."]},{"day":"Day 3","title":"Relaxation in Sharm","details":["Free day by the Red Sea with hotel activities and optional tours.","Evening visit can be arranged to Naama Bay or Soho Square."]},{"day":"Day 4","title":"Sharm Free Time / Bus to Cairo","details":["Free day at the hotel.","Late-night departure to Cairo by bus at 00:15."]},{"day":"Day 5","title":"Cairo Tour","details":["Arrival to Cairo in the morning.","Included tour: Giza Pyramids, Great Sphinx and Grand Egyptian Museum.","Hotel transfer and optional Nile dinner cruise in the evening."]},{"day":"Day 6","title":"Departure","details":["Breakfast and check-out.","Transfer to the airport for the Istanbul flight."]}]'::jsonb,
  '["Flight tickets and airport taxes","4 nights all-inclusive accommodation in Sharm, 1 night bed & breakfast accommodation in Cairo","Airport / hotel / airport transfers","Panoramic city tours","Turkish assistance service","Pyramids tour and Grand Egyptian Museum"]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  2000
WHERE NOT EXISTS (SELECT 1 FROM packages WHERE LOWER(backend_name) = LOWER('5 GECE 6 GÜN SHARM + KAHİRE TURU - 4 GECE SHARM + 1 GECE KAHİRE'));

INSERT INTO packages (title, name, backend_name, route, duration, transfer, transfer_reduction, start_price, programme, price, country, destination, region, force_category, hide_price, card_title, card_subtitle, badge_text, hotel_name, hotel_meal, hotel_nights, sgl_price, dbl_price, tpl_price, package_group_id, package_group_title, package_group_subtitle, package_group_short_title, visibility, image, options, itinerary, included, excluded, flight_details, display_order)
SELECT
  'Turkey Package: 7 Nights / 8 Days Sharm + Cairo',
  'Turkey Package: 7 Nights / 8 Days Sharm + Cairo',
  '7 GECE 8 GÜN SHARM + KAHİRE TURU - 6 GECE SHARM + 1 GECE KAHİRE',
  'Turkey (SAW) → Sharm El Sheikh → Cairo',
  '7 Nights / 8 Days',
  'Flight + Airport Transfers + Bus to Cairo',
  'Flight: 11:00 SAW → SSH Air Cairo / Return 08:00 Cairo → SAW Air Cairo with 30 KG + 8 KG baggage.',
  'From 899 USD',
  'Extra Tours: ATV Safari + Bedouin Night (25$) | Ras Mohammed Boat Trip + Diving (40$) | Water Sports Package (70$) | Dahab Tour (25$) | Nile Dinner Cruise (25$)',
  'From 899 USD',
  'Turkey',
  'Sharm El Sheikh + Cairo',
  'others',
  'others',
  false,
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  'Published',
  '/images/packages/turkey-package-2.webp',
  '[{"title":"Hotel Options / Price Per Person","rows":[{"city":"Sharm + Cairo","nights":"6 + 1","hotel":"Park Regency Resort 5* + Hilton Cairo 5*","meal":"AI + BB","sgl":"+300 USD","dbl":"1049 USD","tpl":"1049 USD"},{"city":"Sharm + Cairo","nights":"6 + 1","hotel":"Marriott Renaissance Golden 5* + Hilton Cairo 5*","meal":"AI + BB","sgl":"+250 USD","dbl":"1029 USD","tpl":"1029 USD"},{"city":"Sharm + Cairo","nights":"6 + 1","hotel":"Safir Waterfalls Resort 5* + Hilton Cairo 5*","meal":"AI + BB","sgl":"+250 USD","dbl":"969 USD","tpl":"969 USD"},{"city":"Sharm + Cairo","nights":"6 + 1","hotel":"Safir Waterfalls Resort 5* + Amarante Pyramids 5*","meal":"AI + BB","sgl":"+200 USD","dbl":"929 USD","tpl":"929 USD"},{"city":"Sharm + Cairo","nights":"6 + 1","hotel":"Queen Sharm Resort 4* + Flamenco Cairo Hotel 4*","meal":"AI + BB","sgl":"+180 USD","dbl":"899 USD","tpl":"899 USD"}]}]'::jsonb,
  '[{"day":"Day 1","title":"Arrival to Sharm El Sheikh","details":["Meeting at Istanbul Sabiha Gökçen Airport and flight to Sharm El Sheikh.","Airport welcome, hotel transfer, check-in and Sharm city tour.","Visits include Old Market, El Sahaba Mosque and Farsha Cafe."]},{"day":"Day 2","title":"Free Day in Sharm","details":["Breakfast and free time at the hotel beach, pool and all-inclusive services.","Optional tours can be arranged during the day."]},{"day":"Day 3","title":"Sharm Activities","details":["Free time to enjoy the Red Sea atmosphere.","Optional ATV Safari, Bedouin Night, Ras Mohammed, diving, water sports or Dahab tour."]},{"day":"Day 4","title":"Sharm Leisure","details":["Relaxing day at the resort.","Optional evening visit to Naama Bay or Soho Square."]},{"day":"Day 5","title":"Sharm Free Day","details":["Enjoy the beach, hotel facilities and optional tours.","Overnight at the Sharm hotel."]},{"day":"Day 6","title":"Night Transfer to Cairo","details":["Free day at the hotel.","Late-night departure to Cairo by bus at 00:15."]},{"day":"Day 7","title":"Cairo Tour","details":["Morning arrival to Cairo.","Included visit: Giza Pyramids, Great Sphinx and Grand Egyptian Museum.","Optional Nile dinner cruise in the evening."]},{"day":"Day 8","title":"Departure","details":["Breakfast and check-out.","Airport transfer and flight back to Istanbul."]}]'::jsonb,
  '["Flight tickets and airport taxes","6 nights all-inclusive accommodation in Sharm, 1 night bed & breakfast accommodation in Cairo","Airport / hotel / airport transfers","Panoramic city tours","Turkish assistance service","Pyramids tour and Grand Egyptian Museum"]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  2001
WHERE NOT EXISTS (SELECT 1 FROM packages WHERE LOWER(backend_name) = LOWER('7 GECE 8 GÜN SHARM + KAHİRE TURU - 6 GECE SHARM + 1 GECE KAHİRE'));

INSERT INTO packages (title, name, backend_name, route, duration, transfer, transfer_reduction, start_price, programme, price, country, destination, region, force_category, hide_price, card_title, card_subtitle, badge_text, hotel_name, hotel_meal, hotel_nights, sgl_price, dbl_price, tpl_price, package_group_id, package_group_title, package_group_subtitle, package_group_short_title, visibility, image, options, itinerary, included, excluded, flight_details, display_order)
SELECT
  'Turkey Package: 7 Nights / 8 Days Sharm + Cairo Deluxe',
  'Turkey Package: 7 Nights / 8 Days Sharm + Cairo Deluxe',
  '7 GECE 8 GÜN SHARM + KAHİRE TURU - 5 GECE SHARM + 2 GECE KAHİRE',
  'Turkey (SAW) → Sharm El Sheikh → Cairo',
  '7 Nights / 8 Days',
  'Flight + Airport Transfers + Cairo Stay',
  'Flight: 11:00 SAW → SSH Air Cairo / Return 08:00 Cairo → SAW Air Cairo with 30 KG + 8 KG baggage.',
  'From 899 USD',
  'Extra Tours: ATV Safari + Bedouin Night (25$) | Ras Mohammed Boat Trip + Diving (40$) | Water Sports Package (70$) | Dahab Tour (25$) | Nile Dinner Cruise (25$)',
  'From 899 USD',
  'Turkey',
  'Sharm El Sheikh + Cairo',
  'others',
  'others',
  false,
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  'Published',
  '/images/packages/turkey-package-3.webp',
  '[{"title":"Hotel Options / Price Per Person","rows":[{"city":"Sharm + Cairo","nights":"5 + 2","hotel":"Park Regency Resort 5* + Hilton Cairo 5*","meal":"AI + BB","sgl":"+300 USD","dbl":"1049 USD","tpl":"1049 USD"},{"city":"Sharm + Cairo","nights":"5 + 2","hotel":"Marriott Renaissance Golden 5* + Hilton Cairo 5*","meal":"AI + BB","sgl":"+250 USD","dbl":"1029 USD","tpl":"1029 USD"},{"city":"Sharm + Cairo","nights":"5 + 2","hotel":"Safir Waterfalls Resort 5* + Hilton Cairo 5*","meal":"AI + BB","sgl":"+250 USD","dbl":"969 USD","tpl":"969 USD"},{"city":"Sharm + Cairo","nights":"5 + 2","hotel":"Safir Waterfalls Resort 5* + Amarante Pyramids 5*","meal":"AI + BB","sgl":"+200 USD","dbl":"929 USD","tpl":"929 USD"},{"city":"Sharm + Cairo","nights":"5 + 2","hotel":"Queen Sharm Resort 4* + Flamenco Cairo Hotel 4*","meal":"AI + BB","sgl":"+180 USD","dbl":"899 USD","tpl":"899 USD"}]}]'::jsonb,
  '[{"day":"Day 1","title":"Arrival to Sharm El Sheikh","details":["Meeting at Istanbul Sabiha Gökçen Airport and flight to Sharm El Sheikh.","Airport welcome, hotel transfer and check-in.","Included Sharm city tour: Old Market, El Sahaba Mosque and Farsha Cafe."]},{"day":"Day 2","title":"Free Day in Sharm","details":["Breakfast and free time at the beach, pool and all-inclusive hotel services.","Optional tours available during the day."]},{"day":"Day 3","title":"Sharm Optional Tours","details":["Enjoy the Red Sea and hotel activities.","Optional ATV Safari, Bedouin Night, Ras Mohammed, diving, water sports or Dahab tour."]},{"day":"Day 4","title":"Sharm Leisure","details":["Free day at the resort.","Optional evening visit to Naama Bay or Soho Square."]},{"day":"Day 5","title":"Last Day in Sharm","details":["Free time to enjoy the resort facilities.","Overnight at the Sharm hotel."]},{"day":"Day 6","title":"Transfer to Cairo","details":["Morning departure to Cairo.","Hotel transfer and check-in.","Included Old Cairo and El Hussein area visit."]},{"day":"Day 7","title":"Pyramids and Museum","details":["Included tour: Pyramids, Sphinx and Egyptian Museum.","Overnight at the Cairo hotel."]},{"day":"Day 8","title":"Departure","details":["Breakfast and check-out.","Transfer to the airport and return flight to Istanbul."]}]'::jsonb,
  '["Flight tickets and airport taxes","5 nights all-inclusive accommodation in Sharm, 2 nights bed & breakfast accommodation in Cairo","Airport / hotel / airport transfers","Panoramic city tours","Turkish assistance service","Pyramids tour and Egyptian Museum"]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  2002
WHERE NOT EXISTS (SELECT 1 FROM packages WHERE LOWER(backend_name) = LOWER('7 GECE 8 GÜN SHARM + KAHİRE TURU - 5 GECE SHARM + 2 GECE KAHİRE'));

INSERT INTO packages (title, name, backend_name, route, duration, transfer, transfer_reduction, start_price, programme, price, country, destination, region, force_category, hide_price, card_title, card_subtitle, badge_text, hotel_name, hotel_meal, hotel_nights, sgl_price, dbl_price, tpl_price, package_group_id, package_group_title, package_group_subtitle, package_group_short_title, visibility, image, options, itinerary, included, excluded, flight_details, display_order)
SELECT
  'Turkey Package: 5 Nights / 6 Days: Park Regency Resort 5* + Hilton Cairo 5*',
  'Turkey Package: 5 Nights / 6 Days: Park Regency Resort 5* + Hilton Cairo 5*',
  '5 GECE 6 GÜN SHARM + KAHİRE TURU - 4 GECE SHARM + 1 GECE KAHİRE - Park Regency Resort 5* + Hilton Cairo 5*',
  'Turkey (SAW) → Sharm El Sheikh → Cairo',
  '5 Nights / 6 Days',
  'Flight + Airport Transfers + Bus to Cairo',
  'Flight: 11:00 SAW → SSH Air Cairo with 20 KG baggage. Return flight will be confirmed.',
  'From 1149 USD',
  'Extra Tours: ATV Safari + Bedouin Night (25$) | Ras Mohammed Boat Trip + Diving (40$) | Water Sports Package (70$) | Dahab Tour (25$) | Nile Dinner Cruise (25$)',
  'From 1149 USD',
  'Turkey',
  'Sharm El Sheikh + Cairo',
  'others',
  'others',
  false,
  'Turkey Package: 5 Nights / 6 Days',
  '4 Nights in Sharm + 1 Night in Cairo',
  '',
  'Park Regency Resort 5* + Hilton Cairo 5*',
  'AI + BB',
  '4 + 1',
  '+420 USD',
  '1149 USD',
  '1149 USD',
  'turkey-sharm-cairo-5n6d',
  'Turkey Package: 5 Nights / 6 Days',
  '4 Nights in Sharm + 1 Night in Cairo',
  '5 Nights / 6 Days',
  'Published',
  '/images/packages/turkey-package-1.webp',
  '[{"title":"Selected Hotel / Price Per Person","rows":[{"city":"Sharm + Cairo","nights":"4 + 1","hotel":"Park Regency Resort 5* + Hilton Cairo 5*","meal":"AI + BB","sgl":"+420 USD","dbl":"1149 USD","tpl":"1149 USD"}]}]'::jsonb,
  '[{"day":"Day 1","title":"Arrival to Sharm El Sheikh","details":["Meeting at Istanbul Sabiha Gökçen Airport and flight to Sharm El Sheikh.","Airport welcome, hotel transfer and check-in.","Included city tour: Old Market, El Sahaba Mosque and Farsha Cafe."]},{"day":"Day 2","title":"Free Day in Sharm","details":["Breakfast and free time to enjoy the beach, pool and all-inclusive hotel services.","Optional activities: ATV Safari, Bedouin Night, Ras Mohammed boat trip, diving, water sports or Dahab tour."]},{"day":"Day 3","title":"Relaxation in Sharm","details":["Free day by the Red Sea with hotel activities and optional tours.","Evening visit can be arranged to Naama Bay or Soho Square."]},{"day":"Day 4","title":"Sharm Free Time / Bus to Cairo","details":["Free day at the hotel.","Late-night departure to Cairo by bus at 00:15."]},{"day":"Day 5","title":"Cairo Tour","details":["Arrival to Cairo in the morning.","Included tour: Giza Pyramids, Great Sphinx and Grand Egyptian Museum.","Hotel transfer and optional Nile dinner cruise in the evening."]},{"day":"Day 6","title":"Departure","details":["Breakfast and check-out.","Transfer to the airport for the Istanbul flight."]}]'::jsonb,
  '["Flight tickets and airport taxes","4 nights all-inclusive accommodation in Sharm, 1 night bed & breakfast accommodation in Cairo","Airport / hotel / airport transfers","Panoramic city tours","Turkish assistance service","Pyramids tour and Grand Egyptian Museum"]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  2003
WHERE NOT EXISTS (SELECT 1 FROM packages WHERE LOWER(backend_name) = LOWER('5 GECE 6 GÜN SHARM + KAHİRE TURU - 4 GECE SHARM + 1 GECE KAHİRE - Park Regency Resort 5* + Hilton Cairo 5*'));

INSERT INTO packages (title, name, backend_name, route, duration, transfer, transfer_reduction, start_price, programme, price, country, destination, region, force_category, hide_price, card_title, card_subtitle, badge_text, hotel_name, hotel_meal, hotel_nights, sgl_price, dbl_price, tpl_price, package_group_id, package_group_title, package_group_subtitle, package_group_short_title, visibility, image, options, itinerary, included, excluded, flight_details, display_order)
SELECT
  'Turkey Package: 5 Nights / 6 Days: Marriott Renaissance Golden 5* + Hilton Cairo 5*',
  'Turkey Package: 5 Nights / 6 Days: Marriott Renaissance Golden 5* + Hilton Cairo 5*',
  '5 GECE 6 GÜN SHARM + KAHİRE TURU - 4 GECE SHARM + 1 GECE KAHİRE - Marriott Renaissance Golden 5* + Hilton Cairo 5*',
  'Turkey (SAW) → Sharm El Sheikh → Cairo',
  '5 Nights / 6 Days',
  'Flight + Airport Transfers + Bus to Cairo',
  'Flight: 11:00 SAW → SSH Air Cairo with 20 KG baggage. Return flight will be confirmed.',
  'From 1129 USD',
  'Extra Tours: ATV Safari + Bedouin Night (25$) | Ras Mohammed Boat Trip + Diving (40$) | Water Sports Package (70$) | Dahab Tour (25$) | Nile Dinner Cruise (25$)',
  'From 1129 USD',
  'Turkey',
  'Sharm El Sheikh + Cairo',
  'others',
  'others',
  false,
  'Turkey Package: 5 Nights / 6 Days',
  '4 Nights in Sharm + 1 Night in Cairo',
  '',
  'Marriott Renaissance Golden 5* + Hilton Cairo 5*',
  'AI + BB',
  '4 + 1',
  '+400 USD',
  '1129 USD',
  '1129 USD',
  'turkey-sharm-cairo-5n6d',
  'Turkey Package: 5 Nights / 6 Days',
  '4 Nights in Sharm + 1 Night in Cairo',
  '5 Nights / 6 Days',
  'Published',
  '/images/packages/turkey-package-1.webp',
  '[{"title":"Selected Hotel / Price Per Person","rows":[{"city":"Sharm + Cairo","nights":"4 + 1","hotel":"Marriott Renaissance Golden 5* + Hilton Cairo 5*","meal":"AI + BB","sgl":"+400 USD","dbl":"1129 USD","tpl":"1129 USD"}]}]'::jsonb,
  '[{"day":"Day 1","title":"Arrival to Sharm El Sheikh","details":["Meeting at Istanbul Sabiha Gökçen Airport and flight to Sharm El Sheikh.","Airport welcome, hotel transfer and check-in.","Included city tour: Old Market, El Sahaba Mosque and Farsha Cafe."]},{"day":"Day 2","title":"Free Day in Sharm","details":["Breakfast and free time to enjoy the beach, pool and all-inclusive hotel services.","Optional activities: ATV Safari, Bedouin Night, Ras Mohammed boat trip, diving, water sports or Dahab tour."]},{"day":"Day 3","title":"Relaxation in Sharm","details":["Free day by the Red Sea with hotel activities and optional tours.","Evening visit can be arranged to Naama Bay or Soho Square."]},{"day":"Day 4","title":"Sharm Free Time / Bus to Cairo","details":["Free day at the hotel.","Late-night departure to Cairo by bus at 00:15."]},{"day":"Day 5","title":"Cairo Tour","details":["Arrival to Cairo in the morning.","Included tour: Giza Pyramids, Great Sphinx and Grand Egyptian Museum.","Hotel transfer and optional Nile dinner cruise in the evening."]},{"day":"Day 6","title":"Departure","details":["Breakfast and check-out.","Transfer to the airport for the Istanbul flight."]}]'::jsonb,
  '["Flight tickets and airport taxes","4 nights all-inclusive accommodation in Sharm, 1 night bed & breakfast accommodation in Cairo","Airport / hotel / airport transfers","Panoramic city tours","Turkish assistance service","Pyramids tour and Grand Egyptian Museum"]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  2004
WHERE NOT EXISTS (SELECT 1 FROM packages WHERE LOWER(backend_name) = LOWER('5 GECE 6 GÜN SHARM + KAHİRE TURU - 4 GECE SHARM + 1 GECE KAHİRE - Marriott Renaissance Golden 5* + Hilton Cairo 5*'));

INSERT INTO packages (title, name, backend_name, route, duration, transfer, transfer_reduction, start_price, programme, price, country, destination, region, force_category, hide_price, card_title, card_subtitle, badge_text, hotel_name, hotel_meal, hotel_nights, sgl_price, dbl_price, tpl_price, package_group_id, package_group_title, package_group_subtitle, package_group_short_title, visibility, image, options, itinerary, included, excluded, flight_details, display_order)
SELECT
  'Turkey Package: 5 Nights / 6 Days: Safir Waterfalls Resort 5* + Hilton Cairo 5*',
  'Turkey Package: 5 Nights / 6 Days: Safir Waterfalls Resort 5* + Hilton Cairo 5*',
  '5 GECE 6 GÜN SHARM + KAHİRE TURU - 4 GECE SHARM + 1 GECE KAHİRE - Safir Waterfalls Resort 5* + Hilton Cairo 5*',
  'Turkey (SAW) → Sharm El Sheikh → Cairo',
  '5 Nights / 6 Days',
  'Flight + Airport Transfers + Bus to Cairo',
  'Flight: 11:00 SAW → SSH Air Cairo with 20 KG baggage. Return flight will be confirmed.',
  'From 1069 USD',
  'Extra Tours: ATV Safari + Bedouin Night (25$) | Ras Mohammed Boat Trip + Diving (40$) | Water Sports Package (70$) | Dahab Tour (25$) | Nile Dinner Cruise (25$)',
  'From 1069 USD',
  'Turkey',
  'Sharm El Sheikh + Cairo',
  'others',
  'others',
  false,
  'Turkey Package: 5 Nights / 6 Days',
  '4 Nights in Sharm + 1 Night in Cairo',
  '',
  'Safir Waterfalls Resort 5* + Hilton Cairo 5*',
  'AI + BB',
  '4 + 1',
  '+350 USD',
  '1069 USD',
  '1069 USD',
  'turkey-sharm-cairo-5n6d',
  'Turkey Package: 5 Nights / 6 Days',
  '4 Nights in Sharm + 1 Night in Cairo',
  '5 Nights / 6 Days',
  'Published',
  '/images/packages/turkey-package-1.webp',
  '[{"title":"Selected Hotel / Price Per Person","rows":[{"city":"Sharm + Cairo","nights":"4 + 1","hotel":"Safir Waterfalls Resort 5* + Hilton Cairo 5*","meal":"AI + BB","sgl":"+350 USD","dbl":"1069 USD","tpl":"1069 USD"}]}]'::jsonb,
  '[{"day":"Day 1","title":"Arrival to Sharm El Sheikh","details":["Meeting at Istanbul Sabiha Gökçen Airport and flight to Sharm El Sheikh.","Airport welcome, hotel transfer and check-in.","Included city tour: Old Market, El Sahaba Mosque and Farsha Cafe."]},{"day":"Day 2","title":"Free Day in Sharm","details":["Breakfast and free time to enjoy the beach, pool and all-inclusive hotel services.","Optional activities: ATV Safari, Bedouin Night, Ras Mohammed boat trip, diving, water sports or Dahab tour."]},{"day":"Day 3","title":"Relaxation in Sharm","details":["Free day by the Red Sea with hotel activities and optional tours.","Evening visit can be arranged to Naama Bay or Soho Square."]},{"day":"Day 4","title":"Sharm Free Time / Bus to Cairo","details":["Free day at the hotel.","Late-night departure to Cairo by bus at 00:15."]},{"day":"Day 5","title":"Cairo Tour","details":["Arrival to Cairo in the morning.","Included tour: Giza Pyramids, Great Sphinx and Grand Egyptian Museum.","Hotel transfer and optional Nile dinner cruise in the evening."]},{"day":"Day 6","title":"Departure","details":["Breakfast and check-out.","Transfer to the airport for the Istanbul flight."]}]'::jsonb,
  '["Flight tickets and airport taxes","4 nights all-inclusive accommodation in Sharm, 1 night bed & breakfast accommodation in Cairo","Airport / hotel / airport transfers","Panoramic city tours","Turkish assistance service","Pyramids tour and Grand Egyptian Museum"]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  2005
WHERE NOT EXISTS (SELECT 1 FROM packages WHERE LOWER(backend_name) = LOWER('5 GECE 6 GÜN SHARM + KAHİRE TURU - 4 GECE SHARM + 1 GECE KAHİRE - Safir Waterfalls Resort 5* + Hilton Cairo 5*'));

INSERT INTO packages (title, name, backend_name, route, duration, transfer, transfer_reduction, start_price, programme, price, country, destination, region, force_category, hide_price, card_title, card_subtitle, badge_text, hotel_name, hotel_meal, hotel_nights, sgl_price, dbl_price, tpl_price, package_group_id, package_group_title, package_group_subtitle, package_group_short_title, visibility, image, options, itinerary, included, excluded, flight_details, display_order)
SELECT
  'Turkey Package: 5 Nights / 6 Days: Safir Waterfalls Resort 5* + Amarante Pyramids 5*',
  'Turkey Package: 5 Nights / 6 Days: Safir Waterfalls Resort 5* + Amarante Pyramids 5*',
  '5 GECE 6 GÜN SHARM + KAHİRE TURU - 4 GECE SHARM + 1 GECE KAHİRE - Safir Waterfalls Resort 5* + Amarante Pyramids 5*',
  'Turkey (SAW) → Sharm El Sheikh → Cairo',
  '5 Nights / 6 Days',
  'Flight + Airport Transfers + Bus to Cairo',
  'Flight: 11:00 SAW → SSH Air Cairo with 20 KG baggage. Return flight will be confirmed.',
  'From 1029 USD',
  'Extra Tours: ATV Safari + Bedouin Night (25$) | Ras Mohammed Boat Trip + Diving (40$) | Water Sports Package (70$) | Dahab Tour (25$) | Nile Dinner Cruise (25$)',
  'From 1029 USD',
  'Turkey',
  'Sharm El Sheikh + Cairo',
  'others',
  'others',
  false,
  'Turkey Package: 5 Nights / 6 Days',
  '4 Nights in Sharm + 1 Night in Cairo',
  '',
  'Safir Waterfalls Resort 5* + Amarante Pyramids 5*',
  'AI + BB',
  '4 + 1',
  '+340 USD',
  '1029 USD',
  '1029 USD',
  'turkey-sharm-cairo-5n6d',
  'Turkey Package: 5 Nights / 6 Days',
  '4 Nights in Sharm + 1 Night in Cairo',
  '5 Nights / 6 Days',
  'Published',
  '/images/packages/turkey-package-1.webp',
  '[{"title":"Selected Hotel / Price Per Person","rows":[{"city":"Sharm + Cairo","nights":"4 + 1","hotel":"Safir Waterfalls Resort 5* + Amarante Pyramids 5*","meal":"AI + BB","sgl":"+340 USD","dbl":"1029 USD","tpl":"1029 USD"}]}]'::jsonb,
  '[{"day":"Day 1","title":"Arrival to Sharm El Sheikh","details":["Meeting at Istanbul Sabiha Gökçen Airport and flight to Sharm El Sheikh.","Airport welcome, hotel transfer and check-in.","Included city tour: Old Market, El Sahaba Mosque and Farsha Cafe."]},{"day":"Day 2","title":"Free Day in Sharm","details":["Breakfast and free time to enjoy the beach, pool and all-inclusive hotel services.","Optional activities: ATV Safari, Bedouin Night, Ras Mohammed boat trip, diving, water sports or Dahab tour."]},{"day":"Day 3","title":"Relaxation in Sharm","details":["Free day by the Red Sea with hotel activities and optional tours.","Evening visit can be arranged to Naama Bay or Soho Square."]},{"day":"Day 4","title":"Sharm Free Time / Bus to Cairo","details":["Free day at the hotel.","Late-night departure to Cairo by bus at 00:15."]},{"day":"Day 5","title":"Cairo Tour","details":["Arrival to Cairo in the morning.","Included tour: Giza Pyramids, Great Sphinx and Grand Egyptian Museum.","Hotel transfer and optional Nile dinner cruise in the evening."]},{"day":"Day 6","title":"Departure","details":["Breakfast and check-out.","Transfer to the airport for the Istanbul flight."]}]'::jsonb,
  '["Flight tickets and airport taxes","4 nights all-inclusive accommodation in Sharm, 1 night bed & breakfast accommodation in Cairo","Airport / hotel / airport transfers","Panoramic city tours","Turkish assistance service","Pyramids tour and Grand Egyptian Museum"]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  2006
WHERE NOT EXISTS (SELECT 1 FROM packages WHERE LOWER(backend_name) = LOWER('5 GECE 6 GÜN SHARM + KAHİRE TURU - 4 GECE SHARM + 1 GECE KAHİRE - Safir Waterfalls Resort 5* + Amarante Pyramids 5*'));

INSERT INTO packages (title, name, backend_name, route, duration, transfer, transfer_reduction, start_price, programme, price, country, destination, region, force_category, hide_price, card_title, card_subtitle, badge_text, hotel_name, hotel_meal, hotel_nights, sgl_price, dbl_price, tpl_price, package_group_id, package_group_title, package_group_subtitle, package_group_short_title, visibility, image, options, itinerary, included, excluded, flight_details, display_order)
SELECT
  'Turkey Package: 5 Nights / 6 Days: Queen Sharm Resort 4* + Flamenco Cairo Hotel 4*',
  'Turkey Package: 5 Nights / 6 Days: Queen Sharm Resort 4* + Flamenco Cairo Hotel 4*',
  '5 GECE 6 GÜN SHARM + KAHİRE TURU - 4 GECE SHARM + 1 GECE KAHİRE - Queen Sharm Resort 4* + Flamenco Cairo Hotel 4*',
  'Turkey (SAW) → Sharm El Sheikh → Cairo',
  '5 Nights / 6 Days',
  'Flight + Airport Transfers + Bus to Cairo',
  'Flight: 11:00 SAW → SSH Air Cairo with 20 KG baggage. Return flight will be confirmed.',
  'From 999 USD',
  'Extra Tours: ATV Safari + Bedouin Night (25$) | Ras Mohammed Boat Trip + Diving (40$) | Water Sports Package (70$) | Dahab Tour (25$) | Nile Dinner Cruise (25$)',
  'From 999 USD',
  'Turkey',
  'Sharm El Sheikh + Cairo',
  'others',
  'others',
  false,
  'Turkey Package: 5 Nights / 6 Days',
  '4 Nights in Sharm + 1 Night in Cairo',
  '',
  'Queen Sharm Resort 4* + Flamenco Cairo Hotel 4*',
  'AI + BB',
  '4 + 1',
  '+330 USD',
  '999 USD',
  '999 USD',
  'turkey-sharm-cairo-5n6d',
  'Turkey Package: 5 Nights / 6 Days',
  '4 Nights in Sharm + 1 Night in Cairo',
  '5 Nights / 6 Days',
  'Published',
  '/images/packages/turkey-package-1.webp',
  '[{"title":"Selected Hotel / Price Per Person","rows":[{"city":"Sharm + Cairo","nights":"4 + 1","hotel":"Queen Sharm Resort 4* + Flamenco Cairo Hotel 4*","meal":"AI + BB","sgl":"+330 USD","dbl":"999 USD","tpl":"999 USD"}]}]'::jsonb,
  '[{"day":"Day 1","title":"Arrival to Sharm El Sheikh","details":["Meeting at Istanbul Sabiha Gökçen Airport and flight to Sharm El Sheikh.","Airport welcome, hotel transfer and check-in.","Included city tour: Old Market, El Sahaba Mosque and Farsha Cafe."]},{"day":"Day 2","title":"Free Day in Sharm","details":["Breakfast and free time to enjoy the beach, pool and all-inclusive hotel services.","Optional activities: ATV Safari, Bedouin Night, Ras Mohammed boat trip, diving, water sports or Dahab tour."]},{"day":"Day 3","title":"Relaxation in Sharm","details":["Free day by the Red Sea with hotel activities and optional tours.","Evening visit can be arranged to Naama Bay or Soho Square."]},{"day":"Day 4","title":"Sharm Free Time / Bus to Cairo","details":["Free day at the hotel.","Late-night departure to Cairo by bus at 00:15."]},{"day":"Day 5","title":"Cairo Tour","details":["Arrival to Cairo in the morning.","Included tour: Giza Pyramids, Great Sphinx and Grand Egyptian Museum.","Hotel transfer and optional Nile dinner cruise in the evening."]},{"day":"Day 6","title":"Departure","details":["Breakfast and check-out.","Transfer to the airport for the Istanbul flight."]}]'::jsonb,
  '["Flight tickets and airport taxes","4 nights all-inclusive accommodation in Sharm, 1 night bed & breakfast accommodation in Cairo","Airport / hotel / airport transfers","Panoramic city tours","Turkish assistance service","Pyramids tour and Grand Egyptian Museum"]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  2007
WHERE NOT EXISTS (SELECT 1 FROM packages WHERE LOWER(backend_name) = LOWER('5 GECE 6 GÜN SHARM + KAHİRE TURU - 4 GECE SHARM + 1 GECE KAHİRE - Queen Sharm Resort 4* + Flamenco Cairo Hotel 4*'));

INSERT INTO packages (title, name, backend_name, route, duration, transfer, transfer_reduction, start_price, programme, price, country, destination, region, force_category, hide_price, card_title, card_subtitle, badge_text, hotel_name, hotel_meal, hotel_nights, sgl_price, dbl_price, tpl_price, package_group_id, package_group_title, package_group_subtitle, package_group_short_title, visibility, image, options, itinerary, included, excluded, flight_details, display_order)
SELECT
  'Turkey Package: 7 Nights / 8 Days: Park Regency Resort 5* + Hilton Cairo 5*',
  'Turkey Package: 7 Nights / 8 Days: Park Regency Resort 5* + Hilton Cairo 5*',
  '7 GECE 8 GÜN SHARM + KAHİRE TURU - 6 GECE SHARM + 1 GECE KAHİRE - Park Regency Resort 5* + Hilton Cairo 5*',
  'Turkey (SAW) → Sharm El Sheikh → Cairo',
  '7 Nights / 8 Days',
  'Flight + Airport Transfers + Bus to Cairo',
  'Flight: 11:00 SAW → SSH Air Cairo / Return 08:00 Cairo → SAW Air Cairo with 30 KG + 8 KG baggage.',
  'From 1249 USD',
  'Extra Tours: ATV Safari + Bedouin Night (25$) | Ras Mohammed Boat Trip + Diving (40$) | Water Sports Package (70$) | Dahab Tour (25$) | Nile Dinner Cruise (25$)',
  'From 1249 USD',
  'Turkey',
  'Sharm El Sheikh + Cairo',
  'others',
  'others',
  false,
  'Turkey Package: 7 Nights / 8 Days',
  '6 Nights in Sharm + 1 Night in Cairo',
  '',
  'Park Regency Resort 5* + Hilton Cairo 5*',
  'AI + BB',
  '6 + 1',
  '+500 USD',
  '1249 USD',
  '1249 USD',
  'turkey-sharm-cairo-7n8d-6-1',
  'Turkey Package: 7 Nights / 8 Days',
  '6 Nights in Sharm + 1 Night in Cairo',
  '7 Nights / 8 Days',
  'Published',
  '/images/packages/turkey-package-2.webp',
  '[{"title":"Selected Hotel / Price Per Person","rows":[{"city":"Sharm + Cairo","nights":"6 + 1","hotel":"Park Regency Resort 5* + Hilton Cairo 5*","meal":"AI + BB","sgl":"+500 USD","dbl":"1249 USD","tpl":"1249 USD"}]}]'::jsonb,
  '[{"day":"Day 1","title":"Arrival to Sharm El Sheikh","details":["Meeting at Istanbul Sabiha Gökçen Airport and flight to Sharm El Sheikh.","Airport welcome, hotel transfer, check-in and Sharm city tour.","Visits include Old Market, El Sahaba Mosque and Farsha Cafe."]},{"day":"Day 2","title":"Free Day in Sharm","details":["Breakfast and free time at the hotel beach, pool and all-inclusive services.","Optional tours can be arranged during the day."]},{"day":"Day 3","title":"Sharm Activities","details":["Free time to enjoy the Red Sea atmosphere.","Optional ATV Safari, Bedouin Night, Ras Mohammed, diving, water sports or Dahab tour."]},{"day":"Day 4","title":"Sharm Leisure","details":["Relaxing day at the resort.","Optional evening visit to Naama Bay or Soho Square."]},{"day":"Day 5","title":"Sharm Free Day","details":["Enjoy the beach, hotel facilities and optional tours.","Overnight at the Sharm hotel."]},{"day":"Day 6","title":"Night Transfer to Cairo","details":["Free day at the hotel.","Late-night departure to Cairo by bus at 00:15."]},{"day":"Day 7","title":"Cairo Tour","details":["Morning arrival to Cairo.","Included visit: Giza Pyramids, Great Sphinx and Grand Egyptian Museum.","Optional Nile dinner cruise in the evening."]},{"day":"Day 8","title":"Departure","details":["Breakfast and check-out.","Airport transfer and flight back to Istanbul."]}]'::jsonb,
  '["Flight tickets and airport taxes","6 nights all-inclusive accommodation in Sharm, 1 night bed & breakfast accommodation in Cairo","Airport / hotel / airport transfers","Panoramic city tours","Turkish assistance service","Pyramids tour and Grand Egyptian Museum"]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  2008
WHERE NOT EXISTS (SELECT 1 FROM packages WHERE LOWER(backend_name) = LOWER('7 GECE 8 GÜN SHARM + KAHİRE TURU - 6 GECE SHARM + 1 GECE KAHİRE - Park Regency Resort 5* + Hilton Cairo 5*'));

INSERT INTO packages (title, name, backend_name, route, duration, transfer, transfer_reduction, start_price, programme, price, country, destination, region, force_category, hide_price, card_title, card_subtitle, badge_text, hotel_name, hotel_meal, hotel_nights, sgl_price, dbl_price, tpl_price, package_group_id, package_group_title, package_group_subtitle, package_group_short_title, visibility, image, options, itinerary, included, excluded, flight_details, display_order)
SELECT
  'Turkey Package: 7 Nights / 8 Days: Marriott Renaissance Golden 5* + Hilton Cairo 5*',
  'Turkey Package: 7 Nights / 8 Days: Marriott Renaissance Golden 5* + Hilton Cairo 5*',
  '7 GECE 8 GÜN SHARM + KAHİRE TURU - 6 GECE SHARM + 1 GECE KAHİRE - Marriott Renaissance Golden 5* + Hilton Cairo 5*',
  'Turkey (SAW) → Sharm El Sheikh → Cairo',
  '7 Nights / 8 Days',
  'Flight + Airport Transfers + Bus to Cairo',
  'Flight: 11:00 SAW → SSH Air Cairo / Return 08:00 Cairo → SAW Air Cairo with 30 KG + 8 KG baggage.',
  'From 1229 USD',
  'Extra Tours: ATV Safari + Bedouin Night (25$) | Ras Mohammed Boat Trip + Diving (40$) | Water Sports Package (70$) | Dahab Tour (25$) | Nile Dinner Cruise (25$)',
  'From 1229 USD',
  'Turkey',
  'Sharm El Sheikh + Cairo',
  'others',
  'others',
  false,
  'Turkey Package: 7 Nights / 8 Days',
  '6 Nights in Sharm + 1 Night in Cairo',
  '',
  'Marriott Renaissance Golden 5* + Hilton Cairo 5*',
  'AI + BB',
  '6 + 1',
  '+450 USD',
  '1229 USD',
  '1229 USD',
  'turkey-sharm-cairo-7n8d-6-1',
  'Turkey Package: 7 Nights / 8 Days',
  '6 Nights in Sharm + 1 Night in Cairo',
  '7 Nights / 8 Days',
  'Published',
  '/images/packages/turkey-package-2.webp',
  '[{"title":"Selected Hotel / Price Per Person","rows":[{"city":"Sharm + Cairo","nights":"6 + 1","hotel":"Marriott Renaissance Golden 5* + Hilton Cairo 5*","meal":"AI + BB","sgl":"+450 USD","dbl":"1229 USD","tpl":"1229 USD"}]}]'::jsonb,
  '[{"day":"Day 1","title":"Arrival to Sharm El Sheikh","details":["Meeting at Istanbul Sabiha Gökçen Airport and flight to Sharm El Sheikh.","Airport welcome, hotel transfer, check-in and Sharm city tour.","Visits include Old Market, El Sahaba Mosque and Farsha Cafe."]},{"day":"Day 2","title":"Free Day in Sharm","details":["Breakfast and free time at the hotel beach, pool and all-inclusive services.","Optional tours can be arranged during the day."]},{"day":"Day 3","title":"Sharm Activities","details":["Free time to enjoy the Red Sea atmosphere.","Optional ATV Safari, Bedouin Night, Ras Mohammed, diving, water sports or Dahab tour."]},{"day":"Day 4","title":"Sharm Leisure","details":["Relaxing day at the resort.","Optional evening visit to Naama Bay or Soho Square."]},{"day":"Day 5","title":"Sharm Free Day","details":["Enjoy the beach, hotel facilities and optional tours.","Overnight at the Sharm hotel."]},{"day":"Day 6","title":"Night Transfer to Cairo","details":["Free day at the hotel.","Late-night departure to Cairo by bus at 00:15."]},{"day":"Day 7","title":"Cairo Tour","details":["Morning arrival to Cairo.","Included visit: Giza Pyramids, Great Sphinx and Grand Egyptian Museum.","Optional Nile dinner cruise in the evening."]},{"day":"Day 8","title":"Departure","details":["Breakfast and check-out.","Airport transfer and flight back to Istanbul."]}]'::jsonb,
  '["Flight tickets and airport taxes","6 nights all-inclusive accommodation in Sharm, 1 night bed & breakfast accommodation in Cairo","Airport / hotel / airport transfers","Panoramic city tours","Turkish assistance service","Pyramids tour and Grand Egyptian Museum"]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  2009
WHERE NOT EXISTS (SELECT 1 FROM packages WHERE LOWER(backend_name) = LOWER('7 GECE 8 GÜN SHARM + KAHİRE TURU - 6 GECE SHARM + 1 GECE KAHİRE - Marriott Renaissance Golden 5* + Hilton Cairo 5*'));

INSERT INTO packages (title, name, backend_name, route, duration, transfer, transfer_reduction, start_price, programme, price, country, destination, region, force_category, hide_price, card_title, card_subtitle, badge_text, hotel_name, hotel_meal, hotel_nights, sgl_price, dbl_price, tpl_price, package_group_id, package_group_title, package_group_subtitle, package_group_short_title, visibility, image, options, itinerary, included, excluded, flight_details, display_order)
SELECT
  'Turkey Package: 7 Nights / 8 Days: Safir Waterfalls Resort 5* + Hilton Cairo 5*',
  'Turkey Package: 7 Nights / 8 Days: Safir Waterfalls Resort 5* + Hilton Cairo 5*',
  '7 GECE 8 GÜN SHARM + KAHİRE TURU - 6 GECE SHARM + 1 GECE KAHİRE - Safir Waterfalls Resort 5* + Hilton Cairo 5*',
  'Turkey (SAW) → Sharm El Sheikh → Cairo',
  '7 Nights / 8 Days',
  'Flight + Airport Transfers + Bus to Cairo',
  'Flight: 11:00 SAW → SSH Air Cairo / Return 08:00 Cairo → SAW Air Cairo with 30 KG + 8 KG baggage.',
  'From 1169 USD',
  'Extra Tours: ATV Safari + Bedouin Night (25$) | Ras Mohammed Boat Trip + Diving (40$) | Water Sports Package (70$) | Dahab Tour (25$) | Nile Dinner Cruise (25$)',
  'From 1169 USD',
  'Turkey',
  'Sharm El Sheikh + Cairo',
  'others',
  'others',
  false,
  'Turkey Package: 7 Nights / 8 Days',
  '6 Nights in Sharm + 1 Night in Cairo',
  '',
  'Safir Waterfalls Resort 5* + Hilton Cairo 5*',
  'AI + BB',
  '6 + 1',
  '+450 USD',
  '1169 USD',
  '1169 USD',
  'turkey-sharm-cairo-7n8d-6-1',
  'Turkey Package: 7 Nights / 8 Days',
  '6 Nights in Sharm + 1 Night in Cairo',
  '7 Nights / 8 Days',
  'Published',
  '/images/packages/turkey-package-2.webp',
  '[{"title":"Selected Hotel / Price Per Person","rows":[{"city":"Sharm + Cairo","nights":"6 + 1","hotel":"Safir Waterfalls Resort 5* + Hilton Cairo 5*","meal":"AI + BB","sgl":"+450 USD","dbl":"1169 USD","tpl":"1169 USD"}]}]'::jsonb,
  '[{"day":"Day 1","title":"Arrival to Sharm El Sheikh","details":["Meeting at Istanbul Sabiha Gökçen Airport and flight to Sharm El Sheikh.","Airport welcome, hotel transfer, check-in and Sharm city tour.","Visits include Old Market, El Sahaba Mosque and Farsha Cafe."]},{"day":"Day 2","title":"Free Day in Sharm","details":["Breakfast and free time at the hotel beach, pool and all-inclusive services.","Optional tours can be arranged during the day."]},{"day":"Day 3","title":"Sharm Activities","details":["Free time to enjoy the Red Sea atmosphere.","Optional ATV Safari, Bedouin Night, Ras Mohammed, diving, water sports or Dahab tour."]},{"day":"Day 4","title":"Sharm Leisure","details":["Relaxing day at the resort.","Optional evening visit to Naama Bay or Soho Square."]},{"day":"Day 5","title":"Sharm Free Day","details":["Enjoy the beach, hotel facilities and optional tours.","Overnight at the Sharm hotel."]},{"day":"Day 6","title":"Night Transfer to Cairo","details":["Free day at the hotel.","Late-night departure to Cairo by bus at 00:15."]},{"day":"Day 7","title":"Cairo Tour","details":["Morning arrival to Cairo.","Included visit: Giza Pyramids, Great Sphinx and Grand Egyptian Museum.","Optional Nile dinner cruise in the evening."]},{"day":"Day 8","title":"Departure","details":["Breakfast and check-out.","Airport transfer and flight back to Istanbul."]}]'::jsonb,
  '["Flight tickets and airport taxes","6 nights all-inclusive accommodation in Sharm, 1 night bed & breakfast accommodation in Cairo","Airport / hotel / airport transfers","Panoramic city tours","Turkish assistance service","Pyramids tour and Grand Egyptian Museum"]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  2010
WHERE NOT EXISTS (SELECT 1 FROM packages WHERE LOWER(backend_name) = LOWER('7 GECE 8 GÜN SHARM + KAHİRE TURU - 6 GECE SHARM + 1 GECE KAHİRE - Safir Waterfalls Resort 5* + Hilton Cairo 5*'));

INSERT INTO packages (title, name, backend_name, route, duration, transfer, transfer_reduction, start_price, programme, price, country, destination, region, force_category, hide_price, card_title, card_subtitle, badge_text, hotel_name, hotel_meal, hotel_nights, sgl_price, dbl_price, tpl_price, package_group_id, package_group_title, package_group_subtitle, package_group_short_title, visibility, image, options, itinerary, included, excluded, flight_details, display_order)
SELECT
  'Turkey Package: 7 Nights / 8 Days: Safir Waterfalls Resort 5* + Amarante Pyramids 5*',
  'Turkey Package: 7 Nights / 8 Days: Safir Waterfalls Resort 5* + Amarante Pyramids 5*',
  '7 GECE 8 GÜN SHARM + KAHİRE TURU - 6 GECE SHARM + 1 GECE KAHİRE - Safir Waterfalls Resort 5* + Amarante Pyramids 5*',
  'Turkey (SAW) → Sharm El Sheikh → Cairo',
  '7 Nights / 8 Days',
  'Flight + Airport Transfers + Bus to Cairo',
  'Flight: 11:00 SAW → SSH Air Cairo / Return 08:00 Cairo → SAW Air Cairo with 30 KG + 8 KG baggage.',
  'From 1129 USD',
  'Extra Tours: ATV Safari + Bedouin Night (25$) | Ras Mohammed Boat Trip + Diving (40$) | Water Sports Package (70$) | Dahab Tour (25$) | Nile Dinner Cruise (25$)',
  'From 1129 USD',
  'Turkey',
  'Sharm El Sheikh + Cairo',
  'others',
  'others',
  false,
  'Turkey Package: 7 Nights / 8 Days',
  '6 Nights in Sharm + 1 Night in Cairo',
  '',
  'Safir Waterfalls Resort 5* + Amarante Pyramids 5*',
  'AI + BB',
  '6 + 1',
  '+400 USD',
  '1129 USD',
  '1129 USD',
  'turkey-sharm-cairo-7n8d-6-1',
  'Turkey Package: 7 Nights / 8 Days',
  '6 Nights in Sharm + 1 Night in Cairo',
  '7 Nights / 8 Days',
  'Published',
  '/images/packages/turkey-package-2.webp',
  '[{"title":"Selected Hotel / Price Per Person","rows":[{"city":"Sharm + Cairo","nights":"6 + 1","hotel":"Safir Waterfalls Resort 5* + Amarante Pyramids 5*","meal":"AI + BB","sgl":"+400 USD","dbl":"1129 USD","tpl":"1129 USD"}]}]'::jsonb,
  '[{"day":"Day 1","title":"Arrival to Sharm El Sheikh","details":["Meeting at Istanbul Sabiha Gökçen Airport and flight to Sharm El Sheikh.","Airport welcome, hotel transfer, check-in and Sharm city tour.","Visits include Old Market, El Sahaba Mosque and Farsha Cafe."]},{"day":"Day 2","title":"Free Day in Sharm","details":["Breakfast and free time at the hotel beach, pool and all-inclusive services.","Optional tours can be arranged during the day."]},{"day":"Day 3","title":"Sharm Activities","details":["Free time to enjoy the Red Sea atmosphere.","Optional ATV Safari, Bedouin Night, Ras Mohammed, diving, water sports or Dahab tour."]},{"day":"Day 4","title":"Sharm Leisure","details":["Relaxing day at the resort.","Optional evening visit to Naama Bay or Soho Square."]},{"day":"Day 5","title":"Sharm Free Day","details":["Enjoy the beach, hotel facilities and optional tours.","Overnight at the Sharm hotel."]},{"day":"Day 6","title":"Night Transfer to Cairo","details":["Free day at the hotel.","Late-night departure to Cairo by bus at 00:15."]},{"day":"Day 7","title":"Cairo Tour","details":["Morning arrival to Cairo.","Included visit: Giza Pyramids, Great Sphinx and Grand Egyptian Museum.","Optional Nile dinner cruise in the evening."]},{"day":"Day 8","title":"Departure","details":["Breakfast and check-out.","Airport transfer and flight back to Istanbul."]}]'::jsonb,
  '["Flight tickets and airport taxes","6 nights all-inclusive accommodation in Sharm, 1 night bed & breakfast accommodation in Cairo","Airport / hotel / airport transfers","Panoramic city tours","Turkish assistance service","Pyramids tour and Grand Egyptian Museum"]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  2011
WHERE NOT EXISTS (SELECT 1 FROM packages WHERE LOWER(backend_name) = LOWER('7 GECE 8 GÜN SHARM + KAHİRE TURU - 6 GECE SHARM + 1 GECE KAHİRE - Safir Waterfalls Resort 5* + Amarante Pyramids 5*'));

INSERT INTO packages (title, name, backend_name, route, duration, transfer, transfer_reduction, start_price, programme, price, country, destination, region, force_category, hide_price, card_title, card_subtitle, badge_text, hotel_name, hotel_meal, hotel_nights, sgl_price, dbl_price, tpl_price, package_group_id, package_group_title, package_group_subtitle, package_group_short_title, visibility, image, options, itinerary, included, excluded, flight_details, display_order)
SELECT
  'Turkey Package: 7 Nights / 8 Days: Queen Sharm Resort 4* + Flamenco Cairo Hotel 4*',
  'Turkey Package: 7 Nights / 8 Days: Queen Sharm Resort 4* + Flamenco Cairo Hotel 4*',
  '7 GECE 8 GÜN SHARM + KAHİRE TURU - 6 GECE SHARM + 1 GECE KAHİRE - Queen Sharm Resort 4* + Flamenco Cairo Hotel 4*',
  'Turkey (SAW) → Sharm El Sheikh → Cairo',
  '7 Nights / 8 Days',
  'Flight + Airport Transfers + Bus to Cairo',
  'Flight: 11:00 SAW → SSH Air Cairo / Return 08:00 Cairo → SAW Air Cairo with 30 KG + 8 KG baggage.',
  'From 1099 USD',
  'Extra Tours: ATV Safari + Bedouin Night (25$) | Ras Mohammed Boat Trip + Diving (40$) | Water Sports Package (70$) | Dahab Tour (25$) | Nile Dinner Cruise (25$)',
  'From 1099 USD',
  'Turkey',
  'Sharm El Sheikh + Cairo',
  'others',
  'others',
  false,
  'Turkey Package: 7 Nights / 8 Days',
  '6 Nights in Sharm + 1 Night in Cairo',
  '',
  'Queen Sharm Resort 4* + Flamenco Cairo Hotel 4*',
  'AI + BB',
  '6 + 1',
  '+380 USD',
  '1099 USD',
  '1099 USD',
  'turkey-sharm-cairo-7n8d-6-1',
  'Turkey Package: 7 Nights / 8 Days',
  '6 Nights in Sharm + 1 Night in Cairo',
  '7 Nights / 8 Days',
  'Published',
  '/images/packages/turkey-package-2.webp',
  '[{"title":"Selected Hotel / Price Per Person","rows":[{"city":"Sharm + Cairo","nights":"6 + 1","hotel":"Queen Sharm Resort 4* + Flamenco Cairo Hotel 4*","meal":"AI + BB","sgl":"+380 USD","dbl":"1099 USD","tpl":"1099 USD"}]}]'::jsonb,
  '[{"day":"Day 1","title":"Arrival to Sharm El Sheikh","details":["Meeting at Istanbul Sabiha Gökçen Airport and flight to Sharm El Sheikh.","Airport welcome, hotel transfer, check-in and Sharm city tour.","Visits include Old Market, El Sahaba Mosque and Farsha Cafe."]},{"day":"Day 2","title":"Free Day in Sharm","details":["Breakfast and free time at the hotel beach, pool and all-inclusive services.","Optional tours can be arranged during the day."]},{"day":"Day 3","title":"Sharm Activities","details":["Free time to enjoy the Red Sea atmosphere.","Optional ATV Safari, Bedouin Night, Ras Mohammed, diving, water sports or Dahab tour."]},{"day":"Day 4","title":"Sharm Leisure","details":["Relaxing day at the resort.","Optional evening visit to Naama Bay or Soho Square."]},{"day":"Day 5","title":"Sharm Free Day","details":["Enjoy the beach, hotel facilities and optional tours.","Overnight at the Sharm hotel."]},{"day":"Day 6","title":"Night Transfer to Cairo","details":["Free day at the hotel.","Late-night departure to Cairo by bus at 00:15."]},{"day":"Day 7","title":"Cairo Tour","details":["Morning arrival to Cairo.","Included visit: Giza Pyramids, Great Sphinx and Grand Egyptian Museum.","Optional Nile dinner cruise in the evening."]},{"day":"Day 8","title":"Departure","details":["Breakfast and check-out.","Airport transfer and flight back to Istanbul."]}]'::jsonb,
  '["Flight tickets and airport taxes","6 nights all-inclusive accommodation in Sharm, 1 night bed & breakfast accommodation in Cairo","Airport / hotel / airport transfers","Panoramic city tours","Turkish assistance service","Pyramids tour and Grand Egyptian Museum"]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  2012
WHERE NOT EXISTS (SELECT 1 FROM packages WHERE LOWER(backend_name) = LOWER('7 GECE 8 GÜN SHARM + KAHİRE TURU - 6 GECE SHARM + 1 GECE KAHİRE - Queen Sharm Resort 4* + Flamenco Cairo Hotel 4*'));

INSERT INTO packages (title, name, backend_name, route, duration, transfer, transfer_reduction, start_price, programme, price, country, destination, region, force_category, hide_price, card_title, card_subtitle, badge_text, hotel_name, hotel_meal, hotel_nights, sgl_price, dbl_price, tpl_price, package_group_id, package_group_title, package_group_subtitle, package_group_short_title, visibility, image, options, itinerary, included, excluded, flight_details, display_order)
SELECT
  'Turkey Package: 7 Nights / 8 Days Deluxe: Park Regency Resort 5* + Hilton Cairo 5*',
  'Turkey Package: 7 Nights / 8 Days Deluxe: Park Regency Resort 5* + Hilton Cairo 5*',
  '7 GECE 8 GÜN SHARM + KAHİRE TURU - 5 GECE SHARM + 2 GECE KAHİRE - Park Regency Resort 5* + Hilton Cairo 5*',
  'Turkey (SAW) → Sharm El Sheikh → Cairo',
  '7 Nights / 8 Days',
  'Flight + Airport Transfers + Bus to Cairo',
  'Flight: 11:00 SAW → SSH Air Cairo / Return 08:00 Cairo → SAW Air Cairo with 30 KG + 8 KG baggage.',
  'From 1249 USD',
  'Extra Tours: ATV Safari + Bedouin Night (25$) | Ras Mohammed Boat Trip + Diving (40$) | Water Sports Package (70$) | Dahab Tour (25$) | Nile Dinner Cruise (25$)',
  'From 1249 USD',
  'Turkey',
  'Sharm El Sheikh + Cairo',
  'others',
  'others',
  false,
  'Turkey Package: 7 Nights / 8 Days Deluxe',
  '5 Nights in Sharm + 2 Nights in Cairo',
  '',
  'Park Regency Resort 5* + Hilton Cairo 5*',
  'AI + BB',
  '5 + 2',
  '+500 USD',
  '1249 USD',
  '1249 USD',
  'turkey-sharm-cairo-7n8d-5-2',
  'Turkey Package: 7 Nights / 8 Days Deluxe',
  '5 Nights in Sharm + 2 Nights in Cairo',
  '7 Nights / 8 Days Deluxe',
  'Published',
  '/images/packages/turkey-package-3.webp',
  '[{"title":"Selected Hotel / Price Per Person","rows":[{"city":"Sharm + Cairo","nights":"5 + 2","hotel":"Park Regency Resort 5* + Hilton Cairo 5*","meal":"AI + BB","sgl":"+500 USD","dbl":"1249 USD","tpl":"1249 USD"}]}]'::jsonb,
  '[{"day":"Day 1","title":"Arrival to Sharm El Sheikh","details":["Meeting at Istanbul Sabiha Gökçen Airport and flight to Sharm El Sheikh.","Airport welcome, hotel transfer and check-in.","Included Sharm city tour: Old Market, El Sahaba Mosque and Farsha Cafe."]},{"day":"Day 2","title":"Free Day in Sharm","details":["Breakfast and free time at the beach, pool and all-inclusive hotel services.","Optional tours available during the day."]},{"day":"Day 3","title":"Sharm Optional Tours","details":["Enjoy the Red Sea and hotel activities.","Optional ATV Safari, Bedouin Night, Ras Mohammed, diving, water sports or Dahab tour."]},{"day":"Day 4","title":"Sharm Leisure","details":["Free day at the resort.","Optional evening visit to Naama Bay or Soho Square."]},{"day":"Day 5","title":"Last Day in Sharm","details":["Free time to enjoy the resort facilities.","Overnight at the Sharm hotel."]},{"day":"Day 6","title":"Transfer to Cairo","details":["Morning departure to Cairo.","Hotel transfer and check-in.","Included Old Cairo and El Hussein area visit."]},{"day":"Day 7","title":"Pyramids and Museum","details":["Included tour: Pyramids, Sphinx and Egyptian Museum.","Overnight at the Cairo hotel."]},{"day":"Day 8","title":"Departure","details":["Breakfast and check-out.","Transfer to the airport and return flight to Istanbul."]}]'::jsonb,
  '["Flight tickets and airport taxes","5 nights all-inclusive accommodation in Sharm, 2 nights bed & breakfast accommodation in Cairo","Airport / hotel / airport transfers","Panoramic city tours","Turkish assistance service","Pyramids tour and Egyptian Museum"]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  2013
WHERE NOT EXISTS (SELECT 1 FROM packages WHERE LOWER(backend_name) = LOWER('7 GECE 8 GÜN SHARM + KAHİRE TURU - 5 GECE SHARM + 2 GECE KAHİRE - Park Regency Resort 5* + Hilton Cairo 5*'));

INSERT INTO packages (title, name, backend_name, route, duration, transfer, transfer_reduction, start_price, programme, price, country, destination, region, force_category, hide_price, card_title, card_subtitle, badge_text, hotel_name, hotel_meal, hotel_nights, sgl_price, dbl_price, tpl_price, package_group_id, package_group_title, package_group_subtitle, package_group_short_title, visibility, image, options, itinerary, included, excluded, flight_details, display_order)
SELECT
  'Turkey Package: 7 Nights / 8 Days Deluxe: Marriott Renaissance Golden 5* + Hilton Cairo 5*',
  'Turkey Package: 7 Nights / 8 Days Deluxe: Marriott Renaissance Golden 5* + Hilton Cairo 5*',
  '7 GECE 8 GÜN SHARM + KAHİRE TURU - 5 GECE SHARM + 2 GECE KAHİRE - Marriott Renaissance Golden 5* + Hilton Cairo 5*',
  'Turkey (SAW) → Sharm El Sheikh → Cairo',
  '7 Nights / 8 Days',
  'Flight + Airport Transfers + Bus to Cairo',
  'Flight: 11:00 SAW → SSH Air Cairo / Return 08:00 Cairo → SAW Air Cairo with 30 KG + 8 KG baggage.',
  'From 1229 USD',
  'Extra Tours: ATV Safari + Bedouin Night (25$) | Ras Mohammed Boat Trip + Diving (40$) | Water Sports Package (70$) | Dahab Tour (25$) | Nile Dinner Cruise (25$)',
  'From 1229 USD',
  'Turkey',
  'Sharm El Sheikh + Cairo',
  'others',
  'others',
  false,
  'Turkey Package: 7 Nights / 8 Days Deluxe',
  '5 Nights in Sharm + 2 Nights in Cairo',
  '',
  'Marriott Renaissance Golden 5* + Hilton Cairo 5*',
  'AI + BB',
  '5 + 2',
  '+450 USD',
  '1229 USD',
  '1229 USD',
  'turkey-sharm-cairo-7n8d-5-2',
  'Turkey Package: 7 Nights / 8 Days Deluxe',
  '5 Nights in Sharm + 2 Nights in Cairo',
  '7 Nights / 8 Days Deluxe',
  'Published',
  '/images/packages/turkey-package-3.webp',
  '[{"title":"Selected Hotel / Price Per Person","rows":[{"city":"Sharm + Cairo","nights":"5 + 2","hotel":"Marriott Renaissance Golden 5* + Hilton Cairo 5*","meal":"AI + BB","sgl":"+450 USD","dbl":"1229 USD","tpl":"1229 USD"}]}]'::jsonb,
  '[{"day":"Day 1","title":"Arrival to Sharm El Sheikh","details":["Meeting at Istanbul Sabiha Gökçen Airport and flight to Sharm El Sheikh.","Airport welcome, hotel transfer and check-in.","Included Sharm city tour: Old Market, El Sahaba Mosque and Farsha Cafe."]},{"day":"Day 2","title":"Free Day in Sharm","details":["Breakfast and free time at the beach, pool and all-inclusive hotel services.","Optional tours available during the day."]},{"day":"Day 3","title":"Sharm Optional Tours","details":["Enjoy the Red Sea and hotel activities.","Optional ATV Safari, Bedouin Night, Ras Mohammed, diving, water sports or Dahab tour."]},{"day":"Day 4","title":"Sharm Leisure","details":["Free day at the resort.","Optional evening visit to Naama Bay or Soho Square."]},{"day":"Day 5","title":"Last Day in Sharm","details":["Free time to enjoy the resort facilities.","Overnight at the Sharm hotel."]},{"day":"Day 6","title":"Transfer to Cairo","details":["Morning departure to Cairo.","Hotel transfer and check-in.","Included Old Cairo and El Hussein area visit."]},{"day":"Day 7","title":"Pyramids and Museum","details":["Included tour: Pyramids, Sphinx and Egyptian Museum.","Overnight at the Cairo hotel."]},{"day":"Day 8","title":"Departure","details":["Breakfast and check-out.","Transfer to the airport and return flight to Istanbul."]}]'::jsonb,
  '["Flight tickets and airport taxes","5 nights all-inclusive accommodation in Sharm, 2 nights bed & breakfast accommodation in Cairo","Airport / hotel / airport transfers","Panoramic city tours","Turkish assistance service","Pyramids tour and Egyptian Museum"]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  2014
WHERE NOT EXISTS (SELECT 1 FROM packages WHERE LOWER(backend_name) = LOWER('7 GECE 8 GÜN SHARM + KAHİRE TURU - 5 GECE SHARM + 2 GECE KAHİRE - Marriott Renaissance Golden 5* + Hilton Cairo 5*'));

INSERT INTO packages (title, name, backend_name, route, duration, transfer, transfer_reduction, start_price, programme, price, country, destination, region, force_category, hide_price, card_title, card_subtitle, badge_text, hotel_name, hotel_meal, hotel_nights, sgl_price, dbl_price, tpl_price, package_group_id, package_group_title, package_group_subtitle, package_group_short_title, visibility, image, options, itinerary, included, excluded, flight_details, display_order)
SELECT
  'Turkey Package: 7 Nights / 8 Days Deluxe: Safir Waterfalls Resort 5* + Hilton Cairo 5*',
  'Turkey Package: 7 Nights / 8 Days Deluxe: Safir Waterfalls Resort 5* + Hilton Cairo 5*',
  '7 GECE 8 GÜN SHARM + KAHİRE TURU - 5 GECE SHARM + 2 GECE KAHİRE - Safir Waterfalls Resort 5* + Hilton Cairo 5*',
  'Turkey (SAW) → Sharm El Sheikh → Cairo',
  '7 Nights / 8 Days',
  'Flight + Airport Transfers + Bus to Cairo',
  'Flight: 11:00 SAW → SSH Air Cairo / Return 08:00 Cairo → SAW Air Cairo with 30 KG + 8 KG baggage.',
  'From 1169 USD',
  'Extra Tours: ATV Safari + Bedouin Night (25$) | Ras Mohammed Boat Trip + Diving (40$) | Water Sports Package (70$) | Dahab Tour (25$) | Nile Dinner Cruise (25$)',
  'From 1169 USD',
  'Turkey',
  'Sharm El Sheikh + Cairo',
  'others',
  'others',
  false,
  'Turkey Package: 7 Nights / 8 Days Deluxe',
  '5 Nights in Sharm + 2 Nights in Cairo',
  '',
  'Safir Waterfalls Resort 5* + Hilton Cairo 5*',
  'AI + BB',
  '5 + 2',
  '+450 USD',
  '1169 USD',
  '1169 USD',
  'turkey-sharm-cairo-7n8d-5-2',
  'Turkey Package: 7 Nights / 8 Days Deluxe',
  '5 Nights in Sharm + 2 Nights in Cairo',
  '7 Nights / 8 Days Deluxe',
  'Published',
  '/images/packages/turkey-package-3.webp',
  '[{"title":"Selected Hotel / Price Per Person","rows":[{"city":"Sharm + Cairo","nights":"5 + 2","hotel":"Safir Waterfalls Resort 5* + Hilton Cairo 5*","meal":"AI + BB","sgl":"+450 USD","dbl":"1169 USD","tpl":"1169 USD"}]}]'::jsonb,
  '[{"day":"Day 1","title":"Arrival to Sharm El Sheikh","details":["Meeting at Istanbul Sabiha Gökçen Airport and flight to Sharm El Sheikh.","Airport welcome, hotel transfer and check-in.","Included Sharm city tour: Old Market, El Sahaba Mosque and Farsha Cafe."]},{"day":"Day 2","title":"Free Day in Sharm","details":["Breakfast and free time at the beach, pool and all-inclusive hotel services.","Optional tours available during the day."]},{"day":"Day 3","title":"Sharm Optional Tours","details":["Enjoy the Red Sea and hotel activities.","Optional ATV Safari, Bedouin Night, Ras Mohammed, diving, water sports or Dahab tour."]},{"day":"Day 4","title":"Sharm Leisure","details":["Free day at the resort.","Optional evening visit to Naama Bay or Soho Square."]},{"day":"Day 5","title":"Last Day in Sharm","details":["Free time to enjoy the resort facilities.","Overnight at the Sharm hotel."]},{"day":"Day 6","title":"Transfer to Cairo","details":["Morning departure to Cairo.","Hotel transfer and check-in.","Included Old Cairo and El Hussein area visit."]},{"day":"Day 7","title":"Pyramids and Museum","details":["Included tour: Pyramids, Sphinx and Egyptian Museum.","Overnight at the Cairo hotel."]},{"day":"Day 8","title":"Departure","details":["Breakfast and check-out.","Transfer to the airport and return flight to Istanbul."]}]'::jsonb,
  '["Flight tickets and airport taxes","5 nights all-inclusive accommodation in Sharm, 2 nights bed & breakfast accommodation in Cairo","Airport / hotel / airport transfers","Panoramic city tours","Turkish assistance service","Pyramids tour and Egyptian Museum"]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  2015
WHERE NOT EXISTS (SELECT 1 FROM packages WHERE LOWER(backend_name) = LOWER('7 GECE 8 GÜN SHARM + KAHİRE TURU - 5 GECE SHARM + 2 GECE KAHİRE - Safir Waterfalls Resort 5* + Hilton Cairo 5*'));

INSERT INTO packages (title, name, backend_name, route, duration, transfer, transfer_reduction, start_price, programme, price, country, destination, region, force_category, hide_price, card_title, card_subtitle, badge_text, hotel_name, hotel_meal, hotel_nights, sgl_price, dbl_price, tpl_price, package_group_id, package_group_title, package_group_subtitle, package_group_short_title, visibility, image, options, itinerary, included, excluded, flight_details, display_order)
SELECT
  'Turkey Package: 7 Nights / 8 Days Deluxe: Safir Waterfalls Resort 5* + Amarante Pyramids 5*',
  'Turkey Package: 7 Nights / 8 Days Deluxe: Safir Waterfalls Resort 5* + Amarante Pyramids 5*',
  '7 GECE 8 GÜN SHARM + KAHİRE TURU - 5 GECE SHARM + 2 GECE KAHİRE - Safir Waterfalls Resort 5* + Amarante Pyramids 5*',
  'Turkey (SAW) → Sharm El Sheikh → Cairo',
  '7 Nights / 8 Days',
  'Flight + Airport Transfers + Bus to Cairo',
  'Flight: 11:00 SAW → SSH Air Cairo / Return 08:00 Cairo → SAW Air Cairo with 30 KG + 8 KG baggage.',
  'From 1129 USD',
  'Extra Tours: ATV Safari + Bedouin Night (25$) | Ras Mohammed Boat Trip + Diving (40$) | Water Sports Package (70$) | Dahab Tour (25$) | Nile Dinner Cruise (25$)',
  'From 1129 USD',
  'Turkey',
  'Sharm El Sheikh + Cairo',
  'others',
  'others',
  false,
  'Turkey Package: 7 Nights / 8 Days Deluxe',
  '5 Nights in Sharm + 2 Nights in Cairo',
  '',
  'Safir Waterfalls Resort 5* + Amarante Pyramids 5*',
  'AI + BB',
  '5 + 2',
  '+400 USD',
  '1129 USD',
  '1129 USD',
  'turkey-sharm-cairo-7n8d-5-2',
  'Turkey Package: 7 Nights / 8 Days Deluxe',
  '5 Nights in Sharm + 2 Nights in Cairo',
  '7 Nights / 8 Days Deluxe',
  'Published',
  '/images/packages/turkey-package-3.webp',
  '[{"title":"Selected Hotel / Price Per Person","rows":[{"city":"Sharm + Cairo","nights":"5 + 2","hotel":"Safir Waterfalls Resort 5* + Amarante Pyramids 5*","meal":"AI + BB","sgl":"+400 USD","dbl":"1129 USD","tpl":"1129 USD"}]}]'::jsonb,
  '[{"day":"Day 1","title":"Arrival to Sharm El Sheikh","details":["Meeting at Istanbul Sabiha Gökçen Airport and flight to Sharm El Sheikh.","Airport welcome, hotel transfer and check-in.","Included Sharm city tour: Old Market, El Sahaba Mosque and Farsha Cafe."]},{"day":"Day 2","title":"Free Day in Sharm","details":["Breakfast and free time at the beach, pool and all-inclusive hotel services.","Optional tours available during the day."]},{"day":"Day 3","title":"Sharm Optional Tours","details":["Enjoy the Red Sea and hotel activities.","Optional ATV Safari, Bedouin Night, Ras Mohammed, diving, water sports or Dahab tour."]},{"day":"Day 4","title":"Sharm Leisure","details":["Free day at the resort.","Optional evening visit to Naama Bay or Soho Square."]},{"day":"Day 5","title":"Last Day in Sharm","details":["Free time to enjoy the resort facilities.","Overnight at the Sharm hotel."]},{"day":"Day 6","title":"Transfer to Cairo","details":["Morning departure to Cairo.","Hotel transfer and check-in.","Included Old Cairo and El Hussein area visit."]},{"day":"Day 7","title":"Pyramids and Museum","details":["Included tour: Pyramids, Sphinx and Egyptian Museum.","Overnight at the Cairo hotel."]},{"day":"Day 8","title":"Departure","details":["Breakfast and check-out.","Transfer to the airport and return flight to Istanbul."]}]'::jsonb,
  '["Flight tickets and airport taxes","5 nights all-inclusive accommodation in Sharm, 2 nights bed & breakfast accommodation in Cairo","Airport / hotel / airport transfers","Panoramic city tours","Turkish assistance service","Pyramids tour and Egyptian Museum"]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  2016
WHERE NOT EXISTS (SELECT 1 FROM packages WHERE LOWER(backend_name) = LOWER('7 GECE 8 GÜN SHARM + KAHİRE TURU - 5 GECE SHARM + 2 GECE KAHİRE - Safir Waterfalls Resort 5* + Amarante Pyramids 5*'));

INSERT INTO packages (title, name, backend_name, route, duration, transfer, transfer_reduction, start_price, programme, price, country, destination, region, force_category, hide_price, card_title, card_subtitle, badge_text, hotel_name, hotel_meal, hotel_nights, sgl_price, dbl_price, tpl_price, package_group_id, package_group_title, package_group_subtitle, package_group_short_title, visibility, image, options, itinerary, included, excluded, flight_details, display_order)
SELECT
  'Turkey Package: 7 Nights / 8 Days Deluxe: Queen Sharm Resort 4* + Flamenco Cairo Hotel 4*',
  'Turkey Package: 7 Nights / 8 Days Deluxe: Queen Sharm Resort 4* + Flamenco Cairo Hotel 4*',
  '7 GECE 8 GÜN SHARM + KAHİRE TURU - 5 GECE SHARM + 2 GECE KAHİRE - Queen Sharm Resort 4* + Flamenco Cairo Hotel 4*',
  'Turkey (SAW) → Sharm El Sheikh → Cairo',
  '7 Nights / 8 Days',
  'Flight + Airport Transfers + Bus to Cairo',
  'Flight: 11:00 SAW → SSH Air Cairo / Return 08:00 Cairo → SAW Air Cairo with 30 KG + 8 KG baggage.',
  'From 1099 USD',
  'Extra Tours: ATV Safari + Bedouin Night (25$) | Ras Mohammed Boat Trip + Diving (40$) | Water Sports Package (70$) | Dahab Tour (25$) | Nile Dinner Cruise (25$)',
  'From 1099 USD',
  'Turkey',
  'Sharm El Sheikh + Cairo',
  'others',
  'others',
  false,
  'Turkey Package: 7 Nights / 8 Days Deluxe',
  '5 Nights in Sharm + 2 Nights in Cairo',
  '',
  'Queen Sharm Resort 4* + Flamenco Cairo Hotel 4*',
  'AI + BB',
  '5 + 2',
  '+380 USD',
  '1099 USD',
  '1099 USD',
  'turkey-sharm-cairo-7n8d-5-2',
  'Turkey Package: 7 Nights / 8 Days Deluxe',
  '5 Nights in Sharm + 2 Nights in Cairo',
  '7 Nights / 8 Days Deluxe',
  'Published',
  '/images/packages/turkey-package-3.webp',
  '[{"title":"Selected Hotel / Price Per Person","rows":[{"city":"Sharm + Cairo","nights":"5 + 2","hotel":"Queen Sharm Resort 4* + Flamenco Cairo Hotel 4*","meal":"AI + BB","sgl":"+380 USD","dbl":"1099 USD","tpl":"1099 USD"}]}]'::jsonb,
  '[{"day":"Day 1","title":"Arrival to Sharm El Sheikh","details":["Meeting at Istanbul Sabiha Gökçen Airport and flight to Sharm El Sheikh.","Airport welcome, hotel transfer and check-in.","Included Sharm city tour: Old Market, El Sahaba Mosque and Farsha Cafe."]},{"day":"Day 2","title":"Free Day in Sharm","details":["Breakfast and free time at the beach, pool and all-inclusive hotel services.","Optional tours available during the day."]},{"day":"Day 3","title":"Sharm Optional Tours","details":["Enjoy the Red Sea and hotel activities.","Optional ATV Safari, Bedouin Night, Ras Mohammed, diving, water sports or Dahab tour."]},{"day":"Day 4","title":"Sharm Leisure","details":["Free day at the resort.","Optional evening visit to Naama Bay or Soho Square."]},{"day":"Day 5","title":"Last Day in Sharm","details":["Free time to enjoy the resort facilities.","Overnight at the Sharm hotel."]},{"day":"Day 6","title":"Transfer to Cairo","details":["Morning departure to Cairo.","Hotel transfer and check-in.","Included Old Cairo and El Hussein area visit."]},{"day":"Day 7","title":"Pyramids and Museum","details":["Included tour: Pyramids, Sphinx and Egyptian Museum.","Overnight at the Cairo hotel."]},{"day":"Day 8","title":"Departure","details":["Breakfast and check-out.","Transfer to the airport and return flight to Istanbul."]}]'::jsonb,
  '["Flight tickets and airport taxes","5 nights all-inclusive accommodation in Sharm, 2 nights bed & breakfast accommodation in Cairo","Airport / hotel / airport transfers","Panoramic city tours","Turkish assistance service","Pyramids tour and Egyptian Museum"]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  2017
WHERE NOT EXISTS (SELECT 1 FROM packages WHERE LOWER(backend_name) = LOWER('7 GECE 8 GÜN SHARM + KAHİRE TURU - 5 GECE SHARM + 2 GECE KAHİRE - Queen Sharm Resort 4* + Flamenco Cairo Hotel 4*'));

INSERT INTO packages (title, name, backend_name, route, duration, transfer, transfer_reduction, start_price, programme, price, country, destination, region, force_category, hide_price, card_title, card_subtitle, badge_text, hotel_name, hotel_meal, hotel_nights, sgl_price, dbl_price, tpl_price, package_group_id, package_group_title, package_group_subtitle, package_group_short_title, visibility, image, options, itinerary, included, excluded, flight_details, display_order)
SELECT
  'Turkey & Egypt',
  'Turkey & Egypt',
  'TURKEY & EGYPT - ISTANBUL - SHARM EL-SHEIKH',
  'Cairo → Istanbul → Sharm El-Sheikh → Cairo',
  '11 Days / 10 Nights',
  'International Flight + Hotels + Optional Internal Programme',
  'Every Sunday starting from 12 July',
  '',
  '',
  '',
  'Turkey / Egypt',
  'Istanbul / Sharm El-Sheikh',
  'others',
  'others',
  true,
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  'Published',
  'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?auto=format&fit=crop&w=1600&q=85',
  '[]'::jsonb,
  '[{"day":"Programme","title":"Istanbul & Sharm El-Sheikh","details":["Travel from Cairo to Istanbul.","Enjoy Istanbul stay with optional internal programme.","Continue the holiday in Sharm El-Sheikh.","Return flight back home."]},{"day":"Istanbul","title":"Optional Internal Programme","details":["Sapanca tour.","Old City tour.","Venezia Mega Outlet Mall and 212 Mall.","Princes’ Islands tour.","Shopping malls: Olivium Outlet Mall and Mall of Istanbul."]},{"day":"Sharm El-Sheikh","title":"Red Sea Stay","details":["Relaxation in Sharm El-Sheikh.","Hotel stay in Sharm with beach and resort atmosphere.","Available hotel options include Queen Sharm, Safir Sharm and Park Regency."]}]'::jsonb,
  '["International flight","40 kg baggage, 2 pieces, and 7 kg hand baggage per adult","30 kg baggage and 7 kg hand baggage per child","Hotel accommodation in Istanbul","Hotel accommodation in Sharm El-Sheikh","Travel dates every Sunday starting from 12 July"]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  2018
WHERE NOT EXISTS (SELECT 1 FROM packages WHERE LOWER(backend_name) = LOWER('TURKEY & EGYPT - ISTANBUL - SHARM EL-SHEIKH'));

INSERT INTO packages (title, name, backend_name, route, duration, transfer, transfer_reduction, start_price, programme, price, country, destination, region, force_category, hide_price, card_title, card_subtitle, badge_text, hotel_name, hotel_meal, hotel_nights, sgl_price, dbl_price, tpl_price, package_group_id, package_group_title, package_group_subtitle, package_group_short_title, visibility, image, options, itinerary, included, excluded, flight_details, display_order)
SELECT
  'Turkey Istanbul',
  'Turkey Istanbul',
  'TURKEY ISTANBUL - 8 DAYS / 7 NIGHTS',
  'Cairo → Istanbul → Cairo',
  '8 Days / 7 Nights',
  'Air Arabia Flight + Hotel + Airport Transfers',
  '24 Mar, 18 Apr, 30 May, 27 Jun, 18 Jul, 01 Aug, 08 Aug, 22 Aug, 29 Aug, 05 Sep, 12 Sep, 19 Sep',
  '',
  '',
  '',
  'Turkey',
  'Istanbul',
  'others',
  'others',
  true,
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  'Published',
  'https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b?auto=format&fit=crop&w=1600&q=85',
  '[]'::jsonb,
  '[{"day":"Day 1","title":"Arrival to Istanbul","details":["Reception at the airport.","Transfer to the hotel.","Check-in and free evening at Taksim Square."]},{"day":"Day 2","title":"Old City Tour","details":["Visit Sultan Ahmed area with Arabic speaking guide.","Discover Sultan Ahmed Mosque, Hagia Sophia and Topkapi Palace area.","Evening visit to Venezia Mega Outlet Mall and 212 Mall."]},{"day":"Day 3","title":"Bursa Trip","details":["Morning departure across the Bosphorus Bridge.","Ferry ride in Marmara Sea.","Visit Turkish delight factory, honey shop, Bursa city and Uludag Mountain.","Lunch included in the internal programme."]},{"day":"Day 4","title":"Sapanca Trip","details":["Full day trip to Sapanca Lake and Masukiye forests.","Enjoy nature views and free time.","Lunch included in the internal programme."]},{"day":"Day 5","title":"Shopping Day","details":["Visit Olivium Outlet Mall.","Visit Mall of Istanbul.","Free time for shopping."]},{"day":"Day 6","title":"Bosphorus Tour","details":["Boat trip to see Istanbul landmarks.","Bosphorus tour and Princes’ Islands view from the sea.","See Topkapi Palace area, Hagia Sophia area and Sultan Ahmed Mosque area.","Pass by Besiktas area and visit Via Port Outlet Mall."]},{"day":"Day 7","title":"Free Day","details":["Free day for shopping.","Optional Izmit trip can be arranged."]},{"day":"Day 8","title":"Departure","details":["Morning preparation for check-out.","Transfer to the airport.","Return flight to Cairo."]}]'::jsonb,
  '["7 nights accommodation in Istanbul hotels with breakfast","Air Arabia round trip flight with 2 baggage pieces and 7 kg hand baggage","Airport transfers from and to Istanbul airport","Hotels in Beyoglu / Taksim area","Optional internal programme in Istanbul"]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  2019
WHERE NOT EXISTS (SELECT 1 FROM packages WHERE LOWER(backend_name) = LOWER('TURKEY ISTANBUL - 8 DAYS / 7 NIGHTS'));

INSERT INTO packages (title, name, backend_name, route, duration, transfer, transfer_reduction, start_price, programme, price, country, destination, region, force_category, hide_price, card_title, card_subtitle, badge_text, hotel_name, hotel_meal, hotel_nights, sgl_price, dbl_price, tpl_price, package_group_id, package_group_title, package_group_subtitle, package_group_short_title, visibility, image, options, itinerary, included, excluded, flight_details, display_order)
SELECT
  'Europe Tour',
  'Europe Tour',
  'EUROPE TOUR - PRAGUE - SALZBURG - HALLSTATT - VIENNA - BUDAPEST - BRATISLAVA',
  'Cairo → Prague → Salzburg → Hallstatt → Vienna → Budapest → Bratislava → Cairo',
  '11 Days / 10 Nights',
  'Flight + A/C Coach Transfers + City Tours',
  'July 23 - August 02, 2026',
  '',
  '',
  '',
  'Europe',
  'Europe Tour',
  'others',
  'others',
  true,
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  'Published',
  'https://images.unsplash.com/photo-1519677100203-a0e668c92439?auto=format&fit=crop&w=1600&q=85',
  '[]'::jsonb,
  '[{"day":"Day 1","title":"Cairo to Prague","details":["Departure from Cairo by Egypt Air flight to Prague.","Arrival Prague, meet and assist, transfer to hotel and check-in.","Rest of the day free at leisure.","Overnight in Prague."]},{"day":"Day 2","title":"Prague City Tour","details":["Breakfast at the hotel.","Half day city tour of Prague.","Discover Prague Castle area, State Opera, National Museum area and Wenceslas Square.","Overnight in Prague."]},{"day":"Day 3","title":"Shopping in Prague","details":["Breakfast at the hotel.","Full day shopping tour at Fashion Arena Outlet.","Free time in Prague.","Overnight in Prague."]},{"day":"Day 4","title":"Prague to Salzburg","details":["Breakfast at the hotel and check-out.","Transfer by A/C coach from Prague to Salzburg.","Arrival Salzburg and check-in.","City tour of Salzburg including Mirabelle Palace, Salzburg Cathedral and Old Town.","Overnight in Salzburg."]},{"day":"Day 5","title":"Hallstatt Full Day Tour","details":["Breakfast at the hotel.","Full day tour to Hallstatt.","Visit Hallstatt Lake, old city and Mountain Dachstein area.","Return to Salzburg and overnight."]},{"day":"Day 6","title":"Salzburg to Vienna","details":["Breakfast at the hotel and check-out.","Transfer by A/C coach from Salzburg to Vienna.","Arrival Vienna and check-in.","Rest of the day free at leisure.","Overnight in Vienna."]},{"day":"Day 7","title":"Vienna City Tour","details":["Breakfast at the hotel.","Half day city tour of Vienna.","Visit main city highlights and Schönbrunn from outside.","Free time in city centre.","Overnight in Vienna."]},{"day":"Day 8","title":"Vienna to Budapest","details":["Breakfast at the hotel and check-out.","Transfer by A/C coach from Vienna to Budapest.","Arrival Budapest and check-in.","Rest of the day free at leisure.","Overnight in Budapest."]},{"day":"Day 9","title":"Budapest City Tour","details":["Breakfast at the hotel.","Half day city tour of Budapest.","Visit Buda, Castle District, Matthias Church, Fishermen’s Bastion and Gellért Hill.","Overnight in Budapest."]},{"day":"Day 10","title":"Bratislava Full Day Tour","details":["Breakfast at the hotel.","Full day tour to Bratislava.","Visit Bratislava Castle and Bratislava Old Town.","Free time for shopping.","Overnight in Budapest."]},{"day":"Day 11","title":"Departure","details":["Breakfast at the hotel.","Transfer to the airport for the flight back home."]}]'::jsonb,
  '["Flight ticket Cairo / Prague - Budapest / Cairo by Egypt Air","3 nights in Prague at 4* hotel","2 nights in Salzburg at 4* hotel","2 nights in Vienna at 4* hotel","3 nights in Budapest at 4* hotel","Daily breakfast and city tax at hotels","Transfers between hotels, airports and cities by A/C coach","City tours in Prague, Salzburg, Vienna and Budapest","Full day tour from Salzburg to Hallstatt","Full day tour from Budapest to Bratislava and shopping","Tour leader with the group"]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  2020
WHERE NOT EXISTS (SELECT 1 FROM packages WHERE LOWER(backend_name) = LOWER('EUROPE TOUR - PRAGUE - SALZBURG - HALLSTATT - VIENNA - BUDAPEST - BRATISLAVA'));

INSERT INTO packages (title, name, backend_name, route, duration, transfer, transfer_reduction, start_price, programme, price, country, destination, region, force_category, hide_price, card_title, card_subtitle, badge_text, hotel_name, hotel_meal, hotel_nights, sgl_price, dbl_price, tpl_price, package_group_id, package_group_title, package_group_subtitle, package_group_short_title, visibility, image, options, itinerary, included, excluded, flight_details, display_order)
SELECT
  'France / Belgium / Holland',
  'France / Belgium / Holland',
  'FRANCE BELGIUM HOLLAND - PARIS - BRUGGE - AMSTERDAM',
  'Cairo → Paris → Brugge → Amsterdam → Cairo',
  '07 Days / 06 Nights',
  'Flight + A/C Coach Transfers + City Tours',
  'June 19 to 25, 2026',
  '',
  '',
  '',
  'France / Belgium / Holland',
  'Paris / Brugge / Amsterdam',
  'others',
  'others',
  true,
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  'Published',
  'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1600&q=85',
  '[]'::jsonb,
  '[{"day":"Day 1","title":"Cairo to Paris","details":["Departure from Cairo.","Arrival Paris, meet and assist at Paris airport.","Transfer to the hotel for check-in.","Rest of the day free at leisure or shopping.","Overnight in Paris."]},{"day":"Day 2","title":"Paris City Tour","details":["Breakfast at the hotel.","Departure for Paris city tour.","Seine cruise included.","Free time at leisure.","Overnight in Paris."]},{"day":"Day 3","title":"Disneyland Optional Tour","details":["Breakfast at the hotel.","Optional full day tour to Disneyland Paris.","Round trip transfer and entrance ticket can be arranged.","Overnight in Paris."]},{"day":"Day 4","title":"Paris to Brugge then Amsterdam","details":["Breakfast at the hotel.","Departure by A/C coach to Brugge.","Full day tour of Brugge, one of the oldest towns in Flanders.","Boat ticket included.","Continue to Amsterdam.","Overnight in Amsterdam."]},{"day":"Day 5","title":"Amsterdam City Tour","details":["Breakfast at the hotel.","Full day city tour of Amsterdam.","Canal cruise included.","Visit Volendam Village and the cheese factory.","Overnight in Amsterdam."]},{"day":"Day 6","title":"Shopping Tour","details":["Breakfast at the hotel.","Optional full day shopping tour at Batavia Stad Outlet.","Free time for shopping.","Overnight in Amsterdam."]},{"day":"Day 7","title":"Departure","details":["Breakfast at the hotel and check-out.","Transfer to Amsterdam airport for the flight back home."]}]'::jsonb,
  '["Flight ticket Cairo / Paris - Amsterdam / Cairo by Egypt Air","3 nights in Paris at 4* hotel","3 nights in Amsterdam at 4* hotel","Daily breakfast","Airport / hotel / airport transfers by A/C coach","Transfer from Paris to Amsterdam by A/C coach","Full day city tour of Paris","Full day city tour of Brugge","Full day city tour of Amsterdam","Daily city tax at the hotels","Tour leader with the group"]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  2021
WHERE NOT EXISTS (SELECT 1 FROM packages WHERE LOWER(backend_name) = LOWER('FRANCE BELGIUM HOLLAND - PARIS - BRUGGE - AMSTERDAM'));

INSERT INTO packages (title, name, backend_name, route, duration, transfer, transfer_reduction, start_price, programme, price, country, destination, region, force_category, hide_price, card_title, card_subtitle, badge_text, hotel_name, hotel_meal, hotel_nights, sgl_price, dbl_price, tpl_price, package_group_id, package_group_title, package_group_subtitle, package_group_short_title, visibility, image, options, itinerary, included, excluded, flight_details, display_order)
SELECT
  'Francia Paris',
  'Francia Paris',
  'FRANCIA PARIS - JULY 23 TO 28 2026',
  'Cairo → Paris → Bruges → Paris → Cairo',
  '06 Days / 05 Nights',
  'Flight + A/C Coach Transfers + Paris & Bruges Tours',
  'July 23 - July 28, 2026',
  '',
  '',
  '',
  'France',
  'Paris',
  'others',
  'others',
  true,
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  'Published',
  'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1600&q=85',
  '[]'::jsonb,
  '[{"day":"Day 1","title":"Cairo to Paris","details":["Departure from Cairo.","Arrival Paris.","Free time for shopping at La Défense shopping centre mall.","Overnight in Paris."]},{"day":"Day 2","title":"Paris Full Day City Tour","details":["Breakfast at the hotel.","Full day city tour of Paris.","Visit Sacré-Cœur, Opera Square, Place Vendôme, Concorde Square, Champs-Élysées, Arc de Triomphe, Eiffel Tower area, Invalides, Orsay Museum, Louvre area, Notre-Dame area, Sorbonne, Panthéon and Saint-Germain-des-Prés.","Seine cruise included without entrance to Eiffel Tower.","Stop at Champs-Élysées for free time.","Overnight in Paris."]},{"day":"Day 3","title":"Bruges Full Day Tour","details":["Breakfast at the hotel.","Full day tour to Bruges.","Discover one of the oldest towns of Flanders.","City walk including Our Lady Church area, medieval Beguinage and canal cruise.","Overnight in Paris."]},{"day":"Day 4","title":"Disneyland Optional Tour","details":["Breakfast at the hotel.","Optional full day tour to Disneyland Paris.","Disneyland Park and Walt Disney Studios Park can be arranged.","Overnight in Paris."]},{"day":"Day 5","title":"Shopping Day","details":["Breakfast at the hotel.","Optional shopping tour in Val d’Europe and Primark.","Overnight in Paris."]},{"day":"Day 6","title":"Departure","details":["Breakfast at the hotel and check-out.","Departure to Cairo."]}]'::jsonb,
  '["Airline ticket Cairo / Paris / Cairo by Egypt Air","5 nights in Paris at 4* hotel","Daily breakfast and daily city tax at the hotel","Airport / hotel / airport transfers by A/C coach","Full day city tour of Paris","Full day tour to Bruges","Tour leader with the group"]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  2022
WHERE NOT EXISTS (SELECT 1 FROM packages WHERE LOWER(backend_name) = LOWER('FRANCIA PARIS - JULY 23 TO 28 2026'));

INSERT INTO packages (title, name, backend_name, route, duration, transfer, transfer_reduction, start_price, programme, price, country, destination, region, force_category, hide_price, card_title, card_subtitle, badge_text, hotel_name, hotel_meal, hotel_nights, sgl_price, dbl_price, tpl_price, package_group_id, package_group_title, package_group_subtitle, package_group_short_title, visibility, image, options, itinerary, included, excluded, flight_details, display_order)
SELECT
  'Morocco & Spain',
  'Morocco & Spain',
  'MOROCCO & SPAIN - MARRAKECH - OUZOUD - CASABLANCA - RABAT - FEZ - MEKNES - TANGIER - MALAGA - TORREMOLINOS - GRANADA - SEVILLE - TOLEDO - MADRID',
  'Cairo → Casablanca → Marrakech → Rabat → Tangier → Malaga → Granada → Madrid → Cairo',
  '15 Days / 14 Nights',
  'Flight + A/C Coach Transfers + Ferry Boat + City Tours',
  'August 21 - September 04, 2026',
  '',
  '',
  '',
  'Morocco / Spain',
  'Marrakech / Ouzoud / Casablanca / Rabat / Fez / Meknes / Tangier / Malaga / Torremolinos / Granada / Seville / Toledo / Madrid',
  'others',
  'others',
  true,
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  'Published',
  'https://images.unsplash.com/photo-1539650116574-75c0c6d73f6e?auto=format&fit=crop&w=1600&q=85',
  '[]'::jsonb,
  '[{"day":"Day 1","title":"Cairo to Casablanca then Marrakech","details":["Departure from Cairo by Egypt Air.","Arrival Casablanca, meet and assist at Casablanca Airport.","Transfer by A/C coach to Marrakech.","Arrival Marrakech, check-in at the hotel and free time.","Overnight in Marrakech."]},{"day":"Day 2","title":"Marrakech City Tour","details":["Breakfast at the hotel.","Half day city tour of Marrakech.","Visit Koutoubia, Menara Gardens, Djemaa El Fna, souks and medina.","Overnight in Marrakech."]},{"day":"Day 3","title":"Ouzoud Waterfalls","details":["Breakfast at the hotel.","Full day visit to Ouzoud Waterfalls.","Enjoy waterfalls, nature, Berber villages and scenic views.","Overnight in Marrakech."]},{"day":"Day 4","title":"Marrakech to Casablanca then Rabat","details":["Breakfast at the hotel and check-out.","Transfer from Marrakech to Rabat by A/C coach.","Stop in Casablanca for city tour.","Visit Hassan II Mosque from outside, Mohamed V Square, Central Market, Habbous quarter, Anfa and Corniche.","Overnight in Rabat."]},{"day":"Day 5","title":"Fez and Meknes Full Day Tour","details":["Breakfast at the hotel.","Full day tour to Fez and Meknes.","Visit Bab Mansour, Jewish Quarter, Tombs of Moulay Ismail, Fez medina, tanneries, souks and Bab Boujloud.","Overnight in Rabat."]},{"day":"Day 6","title":"Rabat to Tangier","details":["Breakfast at the hotel and check-out.","Half day city tour of Rabat.","Visit Oudayas Kasbah, Hassan Tower, Mohamed V Mausoleum, Royal Palace and Mechouar.","Transfer from Rabat to Tangier by A/C coach.","Overnight in Tangier."]},{"day":"Day 7","title":"Tangier Free Day","details":["Breakfast at the hotel.","Free day at leisure on the beach.","Overnight in Tangier."]},{"day":"Day 8","title":"Tangier to Malaga","details":["Breakfast at the hotel and check-out.","Transfer to Tangier Port.","Ferry boat from Tangier to Algeciras Port in Spain.","Transfer by A/C coach to Malaga.","Free time in Malaga city centre, old town and beaches.","Overnight in Malaga."]},{"day":"Day 9","title":"Torremolinos Beach Day","details":["Breakfast at the hotel.","Spend the day in Torremolinos beaches.","Free time for nightlife, dining and shopping around Calle San Miguel.","Overnight in Malaga."]},{"day":"Day 10","title":"Malaga to Granada","details":["Breakfast at the hotel and check-out.","Transfer from Malaga to Granada by A/C coach.","Half day city tour of Granada.","Discover Granada and the Alhambra area from outside.","Overnight in Granada."]},{"day":"Day 11","title":"Seville Full Day Tour","details":["Breakfast at the hotel.","Full day tour to Seville.","Explore Seville highlights including Alcázar area, Seville Cathedral area and Giralda.","Overnight in Granada."]},{"day":"Day 12","title":"Free Day in Granada","details":["Breakfast at the hotel.","Free day at leisure in Granada.","Overnight in Granada."]},{"day":"Day 13","title":"Granada to Madrid via Toledo","details":["Breakfast at the hotel and check-out.","Transfer from Granada to Madrid by A/C coach.","Stop in Toledo for half day city tour.","Free time in Madrid in the evening.","Overnight in Madrid."]},{"day":"Day 14","title":"Madrid City Tour","details":["Breakfast at the hotel.","Half day city tour of Madrid.","Visit main city highlights including old Madrid area, Plaza Mayor area and Royal Palace area from outside.","Free time for shopping at Las Rozas outlet.","Overnight in Madrid."]},{"day":"Day 15","title":"Departure","details":["Breakfast at the hotel and check-out.","Transfer to Madrid Airport for the flight back home by Egypt Air."]}]'::jsonb,
  '["Airline ticket Cairo / Casablanca - Madrid / Cairo by Egypt Air","3 nights in Marrakech at 4* hotel","2 nights in Rabat at 4* hotel","2 nights in Tangier at 4* hotel","2 nights in Malaga at 4* hotel","3 nights in Granada at 4* hotel","2 nights in Madrid at 4* hotel","Daily breakfast and city taxes at hotels","Airport / hotel / airport transfers and transfers between cities by A/C coach","Ferry boat between Tangier and Algeciras","City tours of Marrakech, Casablanca and Rabat","Full day tour from Marrakech to Atlas Mountain / Ouzoud area","Full day tour from Rabat to Fez and Meknes","City tours of Granada and Madrid","Full day tour from Granada to Seville","Full day Toledo tour on the way from Granada to Madrid","Tour leader with the group"]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  2023
WHERE NOT EXISTS (SELECT 1 FROM packages WHERE LOWER(backend_name) = LOWER('MOROCCO & SPAIN - MARRAKECH - OUZOUD - CASABLANCA - RABAT - FEZ - MEKNES - TANGIER - MALAGA - TORREMOLINOS - GRANADA - SEVILLE - TOLEDO - MADRID'));

INSERT INTO packages (title, name, backend_name, route, duration, transfer, transfer_reduction, start_price, programme, price, country, destination, region, force_category, hide_price, card_title, card_subtitle, badge_text, hotel_name, hotel_meal, hotel_nights, sgl_price, dbl_price, tpl_price, package_group_id, package_group_title, package_group_subtitle, package_group_short_title, visibility, image, options, itinerary, included, excluded, flight_details, display_order)
SELECT
  'Italy / Switzerland / France / Spain',
  'Italy / Switzerland / France / Spain',
  'ITALY - SWITZERLAND - FRANCE - SPAIN - MILANO - VENICE - COMO - LUGANO - NICE - CANNES - MONTE CARLO - MARSEILLE - BARCELONA',
  'Cairo → Milan → Venice → Como → Lugano → Nice → Cannes → Monte Carlo → Marseille → Barcelona → Cairo',
  '11 Days / 10 Nights',
  'Flight + A/C Coach Transfers + City Tours',
  'July 23 - August 02, 2026',
  '',
  '',
  '',
  'Italy / Switzerland / France / Spain',
  'Milano / Venice / Como / Lugano / Nice / Cannes / Monte Carlo / Marseille / Barcelona',
  'others',
  'others',
  true,
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  'Published',
  'https://images.unsplash.com/photo-1523906834658-6e24ef2386f9?auto=format&fit=crop&w=1600&q=85',
  '[]'::jsonb,
  '[{"day":"Day 1","title":"Cairo to Milan","details":["Departure from Cairo by Egypt Air flight.","Arrival at Milan Airport, meet and assist.","Transfer to the hotel.","Half day city tour of Milan.","Overnight in Milan."]},{"day":"Day 2","title":"Como and Lugano","details":["Breakfast at the hotel.","Full day tour to Como and Lugano.","Visit Como Lake and Lugano Lake on the border between Switzerland and Italy.","Overnight in Milan."]},{"day":"Day 3","title":"Shopping Day","details":["Breakfast at the hotel.","Optional full day shopping at Serravalle Outlet.","Overnight in Milan."]},{"day":"Day 4","title":"Venice Full Day Tour","details":["Breakfast at the hotel.","Full day tour to Venice.","Enjoy the city atmosphere, canals and famous landmarks.","Overnight in Milan."]},{"day":"Day 5","title":"Milan to Nice","details":["Breakfast at the hotel.","Departure from Milan to Nice by A/C coach.","Arrival Nice and check-in at the hotel.","City tour of Nice including Promenade des Anglais, the port and Old Town market.","Overnight in Nice."]},{"day":"Day 6","title":"Monte Carlo Full Day Tour","details":["Breakfast at the hotel.","Full day tour from Nice to Eze, Monaco and Monte Carlo.","Enjoy the French Riviera highlights.","Overnight in Nice."]},{"day":"Day 7","title":"Cannes Full Day Tour","details":["Breakfast at the hotel.","Full day tour from Nice to Cannes.","Visit La Croisette and the Palace of Festivals area.","Return to Nice and free time at night.","Overnight in Nice."]},{"day":"Day 8","title":"Nice to Barcelona via Marseille","details":["Breakfast at the hotel.","Departure from Nice to Barcelona by A/C coach.","Stop on the way for a city tour of Marseille.","Continue to Barcelona, arrival and check-in.","Overnight in Barcelona."]},{"day":"Day 9","title":"Barcelona City Tour","details":["Breakfast at the hotel.","Half day city tour of Barcelona.","Discover Barcelona highlights including Sagrada Família area and Gaudí landmarks.","Free time at leisure.","Overnight in Barcelona."]},{"day":"Day 10","title":"La Roca Village Shopping","details":["Breakfast at the hotel.","Full day shopping at La Roca Village Outlet.","Free time for shopping and great deals.","Overnight in Barcelona."]},{"day":"Day 11","title":"Departure","details":["Breakfast at the hotel and check-out.","Transfer to Barcelona Airport for the flight back home."]}]'::jsonb,
  '["Flight ticket Cairo / Milan - Barcelona / Cairo by Egypt Air","4 nights in Milan at 4* hotel","3 nights in Nice at 4* hotel","3 nights in Barcelona at 4* hotel","Daily breakfast","Airport / hotel transfer in Milan and hotel / airport transfer in Barcelona by A/C coach","Transfers between cities by A/C coach","Daily city taxes at hotels","City tours of Milan, Nice and Barcelona","Full day tour from Milan to Venice","Full day tour from Milan to Como and Lugano","Full day tour from Nice to Cannes and Monte Carlo","City tour of Marseille","La Roca Village shopping outlet in Barcelona","Tour leader with the group"]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  2024
WHERE NOT EXISTS (SELECT 1 FROM packages WHERE LOWER(backend_name) = LOWER('ITALY - SWITZERLAND - FRANCE - SPAIN - MILANO - VENICE - COMO - LUGANO - NICE - CANNES - MONTE CARLO - MARSEILLE - BARCELONA'));
